vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        document_files:
            uri_prefix: /uploads/documents
            upload_destination: '%private_upload_dir_documents_originals%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\PropertyDirectoryNamer
                options:
                    property: document.id
            delete_on_remove: true
            delete_on_update: true
        post_files:
            uri_prefix: /uploads/posts
            upload_destination: '%private_upload_dir_posts%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\PropertyDirectoryNamer
                options:
                    property: post.id
            delete_on_remove: true
            delete_on_update: true
        post_cover:
            uri_prefix: /uploads/posts
            upload_destination: '%private_upload_dir_posts%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\PropertyDirectoryNamer
                options:
                    property: id
            delete_on_remove: true
            delete_on_update: true
        user_avatar:
            uri_prefix: /uploads/users
            upload_destination: '%private_upload_dir_users%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\PropertyDirectoryNamer
                options:
                    property: id
            delete_on_remove: true
            delete_on_update: true
        user_files:
            uri_prefix: /uploads/users
            upload_destination: '%private_upload_dir_users%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\PropertyDirectoryNamer
                options:
                    property: user.id
            delete_on_remove: true
            delete_on_update: true
        chat_files:
            uri_prefix: /uploads/chats
            upload_destination: '%private_upload_dir_chats%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\PropertyDirectoryNamer
                options:
                    property: message.room.id
            delete_on_remove: true
            delete_on_update: true
