<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260804081816 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE inventory_access (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, organization_id INT NOT NULL, category_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6B5B7FFA76ED395 ON inventory_access (user_id)');
        $this->addSql('CREATE INDEX IDX_6B5B7FF32C8A3DE ON inventory_access (organization_id)');
        $this->addSql('CREATE INDEX IDX_6B5B7FF12469DE2 ON inventory_access (category_id)');
        $this->addSql('CREATE INDEX IDX_6B5B7FFB03A8386 ON inventory_access (created_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_inventory_access ON inventory_access (user_id, organization_id, category_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_inventory_access_org_admin ON inventory_access (user_id, organization_id) WHERE (category_id IS NULL)');
        $this->addSql('CREATE TABLE inventory_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(128) NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_inventory_category_name ON inventory_category (name)');
        $this->addSql('CREATE TABLE inventory_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, inventory_number VARCHAR(64) DEFAULT NULL, serial_number VARCHAR(128) DEFAULT NULL, status VARCHAR(32) DEFAULT \'in_stock\' NOT NULL, description TEXT DEFAULT NULL, price NUMERIC(12, 2) DEFAULT NULL, purchased_at DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, category_id INT DEFAULT NULL, organization_id INT NOT NULL, assigned_to_id INT DEFAULT NULL, upd_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_55BDEA3012469DE2 ON inventory_item (category_id)');
        $this->addSql('CREATE INDEX IDX_55BDEA3032C8A3DE ON inventory_item (organization_id)');
        $this->addSql('CREATE INDEX IDX_55BDEA30B03A8386 ON inventory_item (created_by_id)');
        $this->addSql('CREATE INDEX IDX_55BDEA30896DBBDE ON inventory_item (updated_by_id)');
        $this->addSql('CREATE INDEX idx_inventory_item_org_category ON inventory_item (organization_id, category_id)');
        $this->addSql('CREATE INDEX idx_inventory_item_assigned_to ON inventory_item (assigned_to_id)');
        $this->addSql('CREATE INDEX idx_inventory_item_upd ON inventory_item (upd_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_inventory_item_number ON inventory_item (organization_id, inventory_number)');
        $this->addSql('CREATE TABLE inventory_item_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(32) NOT NULL, old_status VARCHAR(32) DEFAULT NULL, new_status VARCHAR(32) DEFAULT NULL, comment VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, item_id INT NOT NULL, changed_by_id INT DEFAULT NULL, old_assigned_to_id INT DEFAULT NULL, new_assigned_to_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_27487B02126F525E ON inventory_item_history (item_id)');
        $this->addSql('CREATE INDEX IDX_27487B02828AD0A0 ON inventory_item_history (changed_by_id)');
        $this->addSql('CREATE INDEX IDX_27487B0282357B65 ON inventory_item_history (old_assigned_to_id)');
        $this->addSql('CREATE INDEX IDX_27487B02C33EC335 ON inventory_item_history (new_assigned_to_id)');
        $this->addSql('CREATE INDEX idx_inventory_item_history_item_created ON inventory_item_history (item_id, created_at)');
        $this->addSql('CREATE TABLE inventory_upd (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number VARCHAR(64) NOT NULL, document_date DATE NOT NULL, supplier VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organization_id INT NOT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B1F1C07A32C8A3DE ON inventory_upd (organization_id)');
        $this->addSql('CREATE INDEX IDX_B1F1C07AB03A8386 ON inventory_upd (created_by_id)');
        $this->addSql('CREATE INDEX idx_inventory_upd_org_number ON inventory_upd (organization_id, number)');
        $this->addSql('CREATE TABLE inventory_upd_file (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) NOT NULL, storage_key VARCHAR(500) NOT NULL, content_type VARCHAR(100) NOT NULL, size_bytes INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, upd_id INT NOT NULL, uploaded_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5D4DD67DA2B28FE8 ON inventory_upd_file (uploaded_by_id)');
        $this->addSql('CREATE INDEX idx_inventory_upd_file_upd ON inventory_upd_file (upd_id)');
        $this->addSql('ALTER TABLE inventory_access ADD CONSTRAINT FK_6B5B7FFA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_access ADD CONSTRAINT FK_6B5B7FF32C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_access ADD CONSTRAINT FK_6B5B7FF12469DE2 FOREIGN KEY (category_id) REFERENCES inventory_category (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_access ADD CONSTRAINT FK_6B5B7FFB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_item ADD CONSTRAINT FK_55BDEA3012469DE2 FOREIGN KEY (category_id) REFERENCES inventory_category (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_item ADD CONSTRAINT FK_55BDEA3032C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_item ADD CONSTRAINT FK_55BDEA30F4BD7827 FOREIGN KEY (assigned_to_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_item ADD CONSTRAINT FK_55BDEA303EBBA168 FOREIGN KEY (upd_id) REFERENCES inventory_upd (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_item ADD CONSTRAINT FK_55BDEA30B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_item ADD CONSTRAINT FK_55BDEA30896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_item_history ADD CONSTRAINT FK_27487B02126F525E FOREIGN KEY (item_id) REFERENCES inventory_item (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_item_history ADD CONSTRAINT FK_27487B02828AD0A0 FOREIGN KEY (changed_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_item_history ADD CONSTRAINT FK_27487B0282357B65 FOREIGN KEY (old_assigned_to_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_item_history ADD CONSTRAINT FK_27487B02C33EC335 FOREIGN KEY (new_assigned_to_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_upd ADD CONSTRAINT FK_B1F1C07A32C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_upd ADD CONSTRAINT FK_B1F1C07AB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_upd_file ADD CONSTRAINT FK_5D4DD67D3EBBA168 FOREIGN KEY (upd_id) REFERENCES inventory_upd (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_upd_file ADD CONSTRAINT FK_5D4DD67DA2B28FE8 FOREIGN KEY (uploaded_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE inventory_access DROP CONSTRAINT FK_6B5B7FFA76ED395');
        $this->addSql('ALTER TABLE inventory_access DROP CONSTRAINT FK_6B5B7FF32C8A3DE');
        $this->addSql('ALTER TABLE inventory_access DROP CONSTRAINT FK_6B5B7FF12469DE2');
        $this->addSql('ALTER TABLE inventory_access DROP CONSTRAINT FK_6B5B7FFB03A8386');
        $this->addSql('ALTER TABLE inventory_item DROP CONSTRAINT FK_55BDEA3012469DE2');
        $this->addSql('ALTER TABLE inventory_item DROP CONSTRAINT FK_55BDEA3032C8A3DE');
        $this->addSql('ALTER TABLE inventory_item DROP CONSTRAINT FK_55BDEA30F4BD7827');
        $this->addSql('ALTER TABLE inventory_item DROP CONSTRAINT FK_55BDEA303EBBA168');
        $this->addSql('ALTER TABLE inventory_item DROP CONSTRAINT FK_55BDEA30B03A8386');
        $this->addSql('ALTER TABLE inventory_item DROP CONSTRAINT FK_55BDEA30896DBBDE');
        $this->addSql('ALTER TABLE inventory_item_history DROP CONSTRAINT FK_27487B02126F525E');
        $this->addSql('ALTER TABLE inventory_item_history DROP CONSTRAINT FK_27487B02828AD0A0');
        $this->addSql('ALTER TABLE inventory_item_history DROP CONSTRAINT FK_27487B0282357B65');
        $this->addSql('ALTER TABLE inventory_item_history DROP CONSTRAINT FK_27487B02C33EC335');
        $this->addSql('ALTER TABLE inventory_upd DROP CONSTRAINT FK_B1F1C07A32C8A3DE');
        $this->addSql('ALTER TABLE inventory_upd DROP CONSTRAINT FK_B1F1C07AB03A8386');
        $this->addSql('ALTER TABLE inventory_upd_file DROP CONSTRAINT FK_5D4DD67D3EBBA168');
        $this->addSql('ALTER TABLE inventory_upd_file DROP CONSTRAINT FK_5D4DD67DA2B28FE8');
        $this->addSql('DROP TABLE inventory_access');
        $this->addSql('DROP TABLE inventory_category');
        $this->addSql('DROP TABLE inventory_item');
        $this->addSql('DROP TABLE inventory_item_history');
        $this->addSql('DROP TABLE inventory_upd');
        $this->addSql('DROP TABLE inventory_upd_file');
    }
}
