<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260902112225 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ack_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, sort INT DEFAULT 0 NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_ack_category_name ON ack_category (name)');
        $this->addSql('CREATE TABLE ack_document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, audience VARCHAR(16) DEFAULT \'ALL\' NOT NULL, deadline DATE DEFAULT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, archived_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, category_id INT NOT NULL, author_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_38B3320E12469DE2 ON ack_document (category_id)');
        $this->addSql('CREATE INDEX IDX_38B3320EF675F31B ON ack_document (author_id)');
        $this->addSql('CREATE INDEX idx_ack_document_visible ON ack_document (deleted_at, archived_at, published_at)');
        $this->addSql('CREATE TABLE ack_document_file (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, storage_key VARCHAR(500) NOT NULL, original_name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, document_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E42F34F2C33F7837 ON ack_document_file (document_id)');
        $this->addSql('CREATE TABLE ack_document_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(16) DEFAULT NULL, comment TEXT DEFAULT NULL, acted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, document_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E523D4ABC33F7837 ON ack_document_user (document_id)');
        $this->addSql('CREATE INDEX IDX_E523D4ABA76ED395 ON ack_document_user (user_id)');
        $this->addSql('CREATE INDEX idx_ack_document_user_document_status ON ack_document_user (document_id, status)');
        $this->addSql('CREATE INDEX idx_ack_document_user_user_status ON ack_document_user (user_id, status)');
        $this->addSql('CREATE UNIQUE INDEX uniq_ack_document_user ON ack_document_user (document_id, user_id)');
        $this->addSql('ALTER TABLE ack_document ADD CONSTRAINT FK_38B3320E12469DE2 FOREIGN KEY (category_id) REFERENCES ack_category (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ack_document ADD CONSTRAINT FK_38B3320EF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ack_document_file ADD CONSTRAINT FK_E42F34F2C33F7837 FOREIGN KEY (document_id) REFERENCES ack_document (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ack_document_user ADD CONSTRAINT FK_E523D4ABC33F7837 FOREIGN KEY (document_id) REFERENCES ack_document (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ack_document_user ADD CONSTRAINT FK_E523D4ABA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ack_document DROP CONSTRAINT FK_38B3320E12469DE2');
        $this->addSql('ALTER TABLE ack_document DROP CONSTRAINT FK_38B3320EF675F31B');
        $this->addSql('ALTER TABLE ack_document_file DROP CONSTRAINT FK_E42F34F2C33F7837');
        $this->addSql('ALTER TABLE ack_document_user DROP CONSTRAINT FK_E523D4ABC33F7837');
        $this->addSql('ALTER TABLE ack_document_user DROP CONSTRAINT FK_E523D4ABA76ED395');
        $this->addSql('DROP TABLE ack_category');
        $this->addSql('DROP TABLE ack_document');
        $this->addSql('DROP TABLE ack_document_file');
        $this->addSql('DROP TABLE ack_document_user');
    }
}
