<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260718085809 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE purchase_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, priority VARCHAR(20) DEFAULT \'NORMAL\' NOT NULL, due_date DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organization_id INT NOT NULL, created_by_id INT DEFAULT NULL, executor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_204D45E632C8A3DE ON purchase_request (organization_id)');
        $this->addSql('CREATE INDEX IDX_204D45E6B03A8386 ON purchase_request (created_by_id)');
        $this->addSql('CREATE INDEX IDX_204D45E68ABD09BB ON purchase_request (executor_id)');
        $this->addSql('CREATE INDEX IDX_204D45E632C8A3DE7B00651C ON purchase_request (organization_id, status)');
        $this->addSql('CREATE INDEX IDX_204D45E67B00651C ON purchase_request (status)');
        $this->addSql('CREATE INDEX IDX_204D45E68B8E8428 ON purchase_request (created_at)');
        $this->addSql('CREATE TABLE purchase_request_comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, purchase_request_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C1B7F39F4E4DEF6F ON purchase_request_comment (purchase_request_id)');
        $this->addSql('CREATE INDEX IDX_C1B7F39FF675F31B ON purchase_request_comment (author_id)');
        $this->addSql('CREATE TABLE purchase_request_file (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, file_name VARCHAR(255) DEFAULT NULL, original_name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, purchase_request_id INT NOT NULL, uploaded_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3722E64A4E4DEF6F ON purchase_request_file (purchase_request_id)');
        $this->addSql('CREATE INDEX IDX_3722E64AA2B28FE8 ON purchase_request_file (uploaded_by_id)');
        $this->addSql('CREATE TABLE purchase_request_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, from_status VARCHAR(50) DEFAULT NULL, to_status VARCHAR(50) NOT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, purchase_request_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7279D1B84E4DEF6F ON purchase_request_history (purchase_request_id)');
        $this->addSql('CREATE INDEX IDX_7279D1B8A76ED395 ON purchase_request_history (user_id)');
        $this->addSql('CREATE TABLE purchase_request_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, quantity NUMERIC(12, 3) NOT NULL, unit VARCHAR(20) NOT NULL, estimated_price NUMERIC(12, 2) NOT NULL, position INT NOT NULL, purchase_request_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A4A6F5444E4DEF6F ON purchase_request_item (purchase_request_id)');
        $this->addSql('ALTER TABLE purchase_request ADD CONSTRAINT FK_204D45E632C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request ADD CONSTRAINT FK_204D45E6B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request ADD CONSTRAINT FK_204D45E68ABD09BB FOREIGN KEY (executor_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request_comment ADD CONSTRAINT FK_C1B7F39F4E4DEF6F FOREIGN KEY (purchase_request_id) REFERENCES purchase_request (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request_comment ADD CONSTRAINT FK_C1B7F39FF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request_file ADD CONSTRAINT FK_3722E64A4E4DEF6F FOREIGN KEY (purchase_request_id) REFERENCES purchase_request (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request_file ADD CONSTRAINT FK_3722E64AA2B28FE8 FOREIGN KEY (uploaded_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request_history ADD CONSTRAINT FK_7279D1B84E4DEF6F FOREIGN KEY (purchase_request_id) REFERENCES purchase_request (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request_history ADD CONSTRAINT FK_7279D1B8A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request_item ADD CONSTRAINT FK_A4A6F5444E4DEF6F FOREIGN KEY (purchase_request_id) REFERENCES purchase_request (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE purchase_request DROP CONSTRAINT FK_204D45E632C8A3DE');
        $this->addSql('ALTER TABLE purchase_request DROP CONSTRAINT FK_204D45E6B03A8386');
        $this->addSql('ALTER TABLE purchase_request DROP CONSTRAINT FK_204D45E68ABD09BB');
        $this->addSql('ALTER TABLE purchase_request_comment DROP CONSTRAINT FK_C1B7F39F4E4DEF6F');
        $this->addSql('ALTER TABLE purchase_request_comment DROP CONSTRAINT FK_C1B7F39FF675F31B');
        $this->addSql('ALTER TABLE purchase_request_file DROP CONSTRAINT FK_3722E64A4E4DEF6F');
        $this->addSql('ALTER TABLE purchase_request_file DROP CONSTRAINT FK_3722E64AA2B28FE8');
        $this->addSql('ALTER TABLE purchase_request_history DROP CONSTRAINT FK_7279D1B84E4DEF6F');
        $this->addSql('ALTER TABLE purchase_request_history DROP CONSTRAINT FK_7279D1B8A76ED395');
        $this->addSql('ALTER TABLE purchase_request_item DROP CONSTRAINT FK_A4A6F5444E4DEF6F');
        $this->addSql('DROP TABLE purchase_request');
        $this->addSql('DROP TABLE purchase_request_comment');
        $this->addSql('DROP TABLE purchase_request_file');
        $this->addSql('DROP TABLE purchase_request_history');
        $this->addSql('DROP TABLE purchase_request_item');
    }
}
