<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260604122006 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE analytics_tko (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, report_date DATE NOT NULL, garbage_trucks_volume NUMERIC(14, 3) DEFAULT NULL, garbage_trucks_weight NUMERIC(14, 3) DEFAULT NULL, containers_volume NUMERIC(14, 3) DEFAULT NULL, scrap_trucks_volume NUMERIC(14, 3) DEFAULT NULL, containers_scrap_weight NUMERIC(14, 3) DEFAULT NULL, vegetation_volume NUMERIC(14, 3) DEFAULT NULL, construction_volume NUMERIC(14, 3) DEFAULT NULL, terminal_volume NUMERIC(14, 3) DEFAULT NULL, subbotniki_volume NUMERIC(14, 3) DEFAULT NULL, bulldozer_work TEXT DEFAULT NULL, equipment_work TEXT DEFAULT NULL, fire_condition TEXT DEFAULT NULL, irrigation TEXT DEFAULT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, polygon_id INT NOT NULL, created_by INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_864742ADDE12AB56 ON analytics_tko (created_by)');
        $this->addSql('CREATE INDEX idx_analytics_tko_report_date ON analytics_tko (report_date)');
        $this->addSql('CREATE INDEX idx_analytics_tko_polygon_id ON analytics_tko (polygon_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_analytics_tko_polygon_date ON analytics_tko (polygon_id, report_date)');
        $this->addSql('CREATE TABLE polygon (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, gps_lat DOUBLE PRECISION DEFAULT NULL, gps_lng DOUBLE PRECISION DEFAULT NULL, contact_name VARCHAR(255) DEFAULT NULL, contact_phone VARCHAR(64) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, sort_order INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_polygon_name ON polygon (name)');
        $this->addSql('ALTER TABLE analytics_tko ADD CONSTRAINT FK_864742AD24C7C0FB FOREIGN KEY (polygon_id) REFERENCES polygon (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_tko ADD CONSTRAINT FK_864742ADDE12AB56 FOREIGN KEY (created_by) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE analytics_tko DROP CONSTRAINT FK_864742AD24C7C0FB');
        $this->addSql('ALTER TABLE analytics_tko DROP CONSTRAINT FK_864742ADDE12AB56');
        $this->addSql('DROP TABLE analytics_tko');
        $this->addSql('DROP TABLE polygon');
    }
}
