<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261002111913 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE kanban_attachment DROP CONSTRAINT fk_39c29c4ff675f31b');
        $this->addSql('ALTER TABLE kanban_attachment DROP CONSTRAINT fk_39c29c4f4acc9a20');
        $this->addSql('ALTER TABLE kanban_board DROP CONSTRAINT fk_aa902b9556f05a68');
        $this->addSql('ALTER TABLE kanban_board DROP CONSTRAINT fk_aa902b95b03a8386');
        $this->addSql('ALTER TABLE kanban_card DROP CONSTRAINT fk_b2140480be8e8ed5');
        $this->addSql('ALTER TABLE kanban_card DROP CONSTRAINT fk_b2140480b03a8386');
        $this->addSql('ALTER TABLE kanban_card DROP CONSTRAINT fk_b214048085ecde76');
        $this->addSql('ALTER TABLE kanban_card DROP CONSTRAINT fk_b214048077be2925');
        $this->addSql('ALTER TABLE kanban_card_activity DROP CONSTRAINT fk_a438482ca76ed395');
        $this->addSql('ALTER TABLE kanban_card_activity DROP CONSTRAINT fk_a438482c4acc9a20');
        $this->addSql('ALTER TABLE kanban_card_assignee DROP CONSTRAINT fk_74d1bd7a4acc9a20');
        $this->addSql('ALTER TABLE kanban_card_assignee DROP CONSTRAINT fk_74d1bd7aa76ed395');
        $this->addSql('ALTER TABLE kanban_card_comment DROP CONSTRAINT fk_b5080921f675f31b');
        $this->addSql('ALTER TABLE kanban_card_comment DROP CONSTRAINT fk_b50809214acc9a20');
        $this->addSql('ALTER TABLE kanban_card_label DROP CONSTRAINT fk_760ee4daf9c2cf7b');
        $this->addSql('ALTER TABLE kanban_card_label DROP CONSTRAINT fk_760ee4dacfb3a910');
        $this->addSql('ALTER TABLE kanban_card_subtask DROP CONSTRAINT fk_aab7f2e34acc9a20');
        $this->addSql('ALTER TABLE kanban_card_subtask DROP CONSTRAINT fk_aab7f2e3a76ed395');
        $this->addSql('ALTER TABLE kanban_column DROP CONSTRAINT fk_157cf286e7ec5785');
        $this->addSql('ALTER TABLE kanban_label DROP CONSTRAINT fk_fc61503ae7ec5785');
        $this->addSql('ALTER TABLE kanban_project DROP CONSTRAINT fk_9cbd85b57e3c61f9');
        $this->addSql('ALTER TABLE kanban_project DROP CONSTRAINT fk_9cbd85b5b03a8386');
        $this->addSql('ALTER TABLE kanban_project_user DROP CONSTRAINT fk_c264cf6a56f05a68');
        $this->addSql('ALTER TABLE kanban_project_user DROP CONSTRAINT fk_c264cf6aa76ed395');
        $this->addSql('ALTER TABLE kanban_project_user DROP CONSTRAINT fk_c264cf6a162cb942');
        $this->addSql('ALTER TABLE kanban_project_user_folder DROP CONSTRAINT fk_6a1fa684a76ed395');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT fk_bf5476caa76ed395');
        $this->addSql('DROP TABLE kanban_attachment');
        $this->addSql('DROP TABLE kanban_board');
        $this->addSql('DROP TABLE kanban_card');
        $this->addSql('DROP TABLE kanban_card_activity');
        $this->addSql('DROP TABLE kanban_card_assignee');
        $this->addSql('DROP TABLE kanban_card_comment');
        $this->addSql('DROP TABLE kanban_card_label');
        $this->addSql('DROP TABLE kanban_card_subtask');
        $this->addSql('DROP TABLE kanban_column');
        $this->addSql('DROP TABLE kanban_label');
        $this->addSql('DROP TABLE kanban_project');
        $this->addSql('DROP TABLE kanban_project_user');
        $this->addSql('DROP TABLE kanban_project_user_folder');
        $this->addSql('DROP TABLE notification');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE kanban_attachment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) NOT NULL, storage_key VARCHAR(500) NOT NULL, content_type VARCHAR(100) NOT NULL, size_bytes INT NOT NULL, context VARCHAR(20) DEFAULT \'info\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, card_id INT NOT NULL, author_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_39c29c4f4acc9a20 ON kanban_attachment (card_id)');
        $this->addSql('CREATE INDEX idx_39c29c4ff675f31b ON kanban_attachment (author_id)');
        $this->addSql('CREATE TABLE kanban_board (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, kanban_project_id INT NOT NULL, created_by_id INT NOT NULL, "position" DOUBLE PRECISION DEFAULT \'0\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_aa902b95b03a8386 ON kanban_board (created_by_id)');
        $this->addSql('CREATE INDEX idx_aa902b9556f05a68 ON kanban_board (kanban_project_id)');
        $this->addSql('CREATE TABLE kanban_card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(500) NOT NULL, description TEXT DEFAULT NULL, "position" DOUBLE PRECISION NOT NULL, due_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, priority VARCHAR(20) DEFAULT NULL, is_archived BOOLEAN DEFAULT false NOT NULL, border_color VARCHAR(20) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, column_id INT NOT NULL, created_by_id INT DEFAULT NULL, archived_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, archived_by_id INT DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_b214048085ecde76 ON kanban_card (completed_by_id)');
        $this->addSql('CREATE INDEX idx_b2140480b03a8386 ON kanban_card (created_by_id)');
        $this->addSql('CREATE INDEX idx_b2140480be8e8ed5 ON kanban_card (column_id)');
        $this->addSql('CREATE INDEX idx_b214048077be2925 ON kanban_card (archived_by_id)');
        $this->addSql('CREATE TABLE kanban_card_activity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(40) NOT NULL, old_value TEXT DEFAULT NULL, new_value TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, card_id INT NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_card_activity_card_created ON kanban_card_activity (card_id, created_at)');
        $this->addSql('CREATE INDEX idx_a438482c4acc9a20 ON kanban_card_activity (card_id)');
        $this->addSql('CREATE INDEX idx_a438482ca76ed395 ON kanban_card_activity (user_id)');
        $this->addSql('CREATE TABLE kanban_card_assignee (card_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (card_id, user_id))');
        $this->addSql('CREATE INDEX idx_74d1bd7a4acc9a20 ON kanban_card_assignee (card_id)');
        $this->addSql('CREATE INDEX idx_74d1bd7aa76ed395 ON kanban_card_assignee (user_id)');
        $this->addSql('CREATE TABLE kanban_card_comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, card_id INT NOT NULL, author_id INT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_b50809214acc9a20 ON kanban_card_comment (card_id)');
        $this->addSql('CREATE INDEX idx_b5080921f675f31b ON kanban_card_comment (author_id)');
        $this->addSql('CREATE TABLE kanban_card_label (kanban_card_id INT NOT NULL, kanban_label_id INT NOT NULL, PRIMARY KEY (kanban_card_id, kanban_label_id))');
        $this->addSql('CREATE INDEX idx_760ee4dacfb3a910 ON kanban_card_label (kanban_label_id)');
        $this->addSql('CREATE INDEX idx_760ee4daf9c2cf7b ON kanban_card_label (kanban_card_id)');
        $this->addSql('CREATE TABLE kanban_card_subtask (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(500) NOT NULL, status VARCHAR(255) DEFAULT \'to_do\' NOT NULL, "position" DOUBLE PRECISION NOT NULL, card_id INT NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_aab7f2e3a76ed395 ON kanban_card_subtask (user_id)');
        $this->addSql('CREATE INDEX idx_aab7f2e34acc9a20 ON kanban_card_subtask (card_id)');
        $this->addSql('CREATE TABLE kanban_column (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, header_color VARCHAR(30) DEFAULT \'bg-primary\' NOT NULL, "position" DOUBLE PRECISION NOT NULL, board_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_157cf286e7ec5785 ON kanban_column (board_id)');
        $this->addSql('CREATE TABLE kanban_label (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, color VARCHAR(30) NOT NULL, board_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_fc61503ae7ec5785 ON kanban_label (board_id)');
        $this->addSql('CREATE TABLE kanban_project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, owner_id INT NOT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_9cbd85b57e3c61f9 ON kanban_project (owner_id)');
        $this->addSql('CREATE INDEX idx_9cbd85b5b03a8386 ON kanban_project (created_by_id)');
        $this->addSql('CREATE TABLE kanban_project_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(255) NOT NULL, kanban_project_id INT NOT NULL, user_id INT NOT NULL, "position" DOUBLE PRECISION DEFAULT \'0\' NOT NULL, folder_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_project_user_folder_position ON kanban_project_user (user_id, folder_id, "position")');
        $this->addSql('CREATE INDEX idx_c264cf6a162cb942 ON kanban_project_user (folder_id)');
        $this->addSql('CREATE INDEX idx_c264cf6a56f05a68 ON kanban_project_user (kanban_project_id)');
        $this->addSql('CREATE INDEX idx_c264cf6aa76ed395 ON kanban_project_user (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_project_user ON kanban_project_user (kanban_project_id, user_id)');
        $this->addSql('CREATE TABLE kanban_project_user_folder (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, "position" DOUBLE PRECISION DEFAULT \'0\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_6a1fa684a76ed395 ON kanban_project_user_folder (user_id)');
        $this->addSql('CREATE INDEX idx_folder_user_position ON kanban_project_user_folder (user_id, "position")');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, title VARCHAR(255) NOT NULL, message TEXT DEFAULT NULL, link VARCHAR(512) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, extra JSON DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_bf5476caa76ed395 ON notification (user_id)');
        $this->addSql('CREATE INDEX idx_notification_user_read ON notification (user_id, read_at)');
        $this->addSql('CREATE INDEX idx_notification_user_created ON notification (user_id, created_at)');
        $this->addSql('ALTER TABLE kanban_attachment ADD CONSTRAINT fk_39c29c4ff675f31b FOREIGN KEY (author_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kanban_attachment ADD CONSTRAINT fk_39c29c4f4acc9a20 FOREIGN KEY (card_id) REFERENCES kanban_card (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kanban_board ADD CONSTRAINT fk_aa902b9556f05a68 FOREIGN KEY (kanban_project_id) REFERENCES kanban_project (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kanban_board ADD CONSTRAINT fk_aa902b95b03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kanban_card ADD CONSTRAINT fk_b2140480be8e8ed5 FOREIGN KEY (column_id) REFERENCES kanban_column (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kanban_card ADD CONSTRAINT fk_b2140480b03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kanban_card ADD CONSTRAINT fk_b214048085ecde76 FOREIGN KEY (completed_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kanban_card ADD CONSTRAINT fk_b214048077be2925 FOREIGN KEY (archived_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kanban_card_activity ADD CONSTRAINT fk_a438482ca76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kanban_card_activity ADD CONSTRAINT fk_a438482c4acc9a20 FOREIGN KEY (card_id) REFERENCES kanban_card (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kanban_card_assignee ADD CONSTRAINT fk_74d1bd7a4acc9a20 FOREIGN KEY (card_id) REFERENCES kanban_card (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kanban_card_assignee ADD CONSTRAINT fk_74d1bd7aa76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kanban_card_comment ADD CONSTRAINT fk_b5080921f675f31b FOREIGN KEY (author_id) REFERENCES "user" (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kanban_card_comment ADD CONSTRAINT fk_b50809214acc9a20 FOREIGN KEY (card_id) REFERENCES kanban_card (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kanban_card_label ADD CONSTRAINT fk_760ee4daf9c2cf7b FOREIGN KEY (kanban_card_id) REFERENCES kanban_card (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kanban_card_label ADD CONSTRAINT fk_760ee4dacfb3a910 FOREIGN KEY (kanban_label_id) REFERENCES kanban_label (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kanban_card_subtask ADD CONSTRAINT fk_aab7f2e34acc9a20 FOREIGN KEY (card_id) REFERENCES kanban_card (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kanban_card_subtask ADD CONSTRAINT fk_aab7f2e3a76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kanban_column ADD CONSTRAINT fk_157cf286e7ec5785 FOREIGN KEY (board_id) REFERENCES kanban_board (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kanban_label ADD CONSTRAINT fk_fc61503ae7ec5785 FOREIGN KEY (board_id) REFERENCES kanban_board (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kanban_project ADD CONSTRAINT fk_9cbd85b57e3c61f9 FOREIGN KEY (owner_id) REFERENCES "user" (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kanban_project ADD CONSTRAINT fk_9cbd85b5b03a8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kanban_project_user ADD CONSTRAINT fk_c264cf6a56f05a68 FOREIGN KEY (kanban_project_id) REFERENCES kanban_project (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kanban_project_user ADD CONSTRAINT fk_c264cf6aa76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kanban_project_user ADD CONSTRAINT fk_c264cf6a162cb942 FOREIGN KEY (folder_id) REFERENCES kanban_project_user_folder (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kanban_project_user_folder ADD CONSTRAINT fk_6a1fa684a76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT fk_bf5476caa76ed395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
