<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260415093157 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE analytics_aggregated_data (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, business_key VARCHAR(128) NOT NULL, metric_name_snapshot VARCHAR(255) DEFAULT NULL, metric_unit_snapshot VARCHAR(64) DEFAULT NULL, metric_type_snapshot VARCHAR(64) DEFAULT NULL, aggregation_type VARCHAR(64) NOT NULL, effective_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, value NUMERIC(20, 4) DEFAULT NULL, value_int INT DEFAULT NULL, aggregated_value_number NUMERIC(20, 4) DEFAULT NULL, source_count INT NOT NULL, calculated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, metric_id INT NOT NULL, board_id INT NOT NULL, report_id INT NOT NULL, period_id INT NOT NULL, organization_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B846BFD1A952D583 ON analytics_aggregated_data (metric_id)');
        $this->addSql('CREATE INDEX IDX_B846BFD1EC8B7ADE ON analytics_aggregated_data (period_id)');
        $this->addSql('CREATE INDEX IDX_B846BFD132C8A3DE ON analytics_aggregated_data (organization_id)');
        $this->addSql('CREATE INDEX idx_analytics_agg_period_org ON analytics_aggregated_data (period_id, organization_id)');
        $this->addSql('CREATE INDEX idx_analytics_agg_business_key_org ON analytics_aggregated_data (business_key, organization_id)');
        $this->addSql('CREATE INDEX idx_analytics_agg_metric_org ON analytics_aggregated_data (metric_id, organization_id)');
        $this->addSql('CREATE INDEX idx_analytics_agg_board ON analytics_aggregated_data (board_id)');
        $this->addSql('CREATE INDEX idx_analytics_agg_report ON analytics_aggregated_data (report_id)');
        $this->addSql('CREATE INDEX idx_analytics_agg_effective_at ON analytics_aggregated_data (effective_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_analytics_agg ON analytics_aggregated_data (metric_id, period_id, organization_id, board_id, report_id)');
        $this->addSql('CREATE TABLE analytics_audit_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(64) NOT NULL, entity_type VARCHAR(64) NOT NULL, entity_id INT NOT NULL, old_value JSON DEFAULT NULL, new_value JSON DEFAULT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_98D0696FA76ED395 ON analytics_audit_log (user_id)');
        $this->addSql('CREATE INDEX idx_analytics_audit_log_entity ON analytics_audit_log (entity_type, entity_id)');
        $this->addSql('CREATE INDEX idx_analytics_audit_log_occurred_at ON analytics_audit_log (occurred_at)');
        $this->addSql('CREATE TABLE analytics_board_version_metrics (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT NOT NULL, is_required BOOLEAN DEFAULT false NOT NULL, board_version_id INT NOT NULL, metric_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_analytics_board_version_metrics_board_version ON analytics_board_version_metrics (board_version_id)');
        $this->addSql('CREATE INDEX idx_analytics_board_version_metrics_metric ON analytics_board_version_metrics (metric_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_analytics_board_version_metrics ON analytics_board_version_metrics (board_version_id, metric_id)');
        $this->addSql('CREATE TABLE analytics_board_versions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, version_number INT NOT NULL, status VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, board_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_analytics_board_versions_board_id ON analytics_board_versions (board_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_analytics_board_versions_board_version ON analytics_board_versions (board_id, version_number)');
        $this->addSql('CREATE TABLE analytics_boards (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE analytics_metrics (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, business_key VARCHAR(128) NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(64) NOT NULL, unit VARCHAR(32) NOT NULL, aggregation_type VARCHAR(16) NOT NULL, input_type VARCHAR(32) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_analytics_metrics_business_key ON analytics_metrics (business_key)');
        $this->addSql('CREATE TABLE analytics_organization_boards (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_required BOOLEAN DEFAULT false NOT NULL, organization_id INT NOT NULL, board_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FA00D52A32C8A3DE ON analytics_organization_boards (organization_id)');
        $this->addSql('CREATE INDEX IDX_FA00D52AE7EC5785 ON analytics_organization_boards (board_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_analytics_organization_boards ON analytics_organization_boards (organization_id, board_id)');
        $this->addSql('CREATE TABLE analytics_periods (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, iso_year INT NOT NULL, iso_week INT NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, is_closed BOOLEAN DEFAULT false NOT NULL, description VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_analytics_periods_start_date ON analytics_periods (start_date)');
        $this->addSql('CREATE UNIQUE INDEX uniq_analytics_periods_iso_year_week ON analytics_periods (iso_year, iso_week)');
        $this->addSql('CREATE TABLE analytics_report_values (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, metric_name_snapshot VARCHAR(255) DEFAULT NULL, metric_unit_snapshot VARCHAR(64) DEFAULT NULL, metric_type_snapshot VARCHAR(64) DEFAULT NULL, value_number NUMERIC(20, 4) DEFAULT NULL, value_text TEXT DEFAULT NULL, value_bool BOOLEAN DEFAULT NULL, value_json JSONB DEFAULT NULL, effective_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, report_id INT NOT NULL, board_version_metric_id INT NOT NULL, created_by INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7B57B5BBDE12AB56 ON analytics_report_values (created_by)');
        $this->addSql('CREATE INDEX idx_analytics_report_values_report_id ON analytics_report_values (report_id)');
        $this->addSql('CREATE INDEX idx_analytics_report_values_board_version_metric_id ON analytics_report_values (board_version_metric_id)');
        $this->addSql('CREATE INDEX idx_analytics_report_values_metric_report ON analytics_report_values (board_version_metric_id, report_id)');
        $this->addSql('CREATE INDEX idx_analytics_report_values_bvm_effective_at ON analytics_report_values (board_version_metric_id, effective_at)');
        $this->addSql('CREATE INDEX idx_analytics_report_values_effective_at ON analytics_report_values (effective_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_analytics_report_values_report_metric ON analytics_report_values (report_id, board_version_metric_id)');
        $this->addSql('CREATE TABLE analytics_reports (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(16) NOT NULL, is_complete BOOLEAN DEFAULT false NOT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, submitted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, approved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, organization_id INT NOT NULL, board_id INT NOT NULL, board_version_id INT NOT NULL, period_id INT NOT NULL, created_by INT NOT NULL, approved_by INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5BBD2BBBE7B2F3B9 ON analytics_reports (board_version_id)');
        $this->addSql('CREATE INDEX IDX_5BBD2BBBDE12AB56 ON analytics_reports (created_by)');
        $this->addSql('CREATE INDEX IDX_5BBD2BBB4EA3CB3D ON analytics_reports (approved_by)');
        $this->addSql('CREATE INDEX idx_analytics_reports_period_id ON analytics_reports (period_id)');
        $this->addSql('CREATE INDEX idx_analytics_reports_organization_id ON analytics_reports (organization_id)');
        $this->addSql('CREATE INDEX idx_analytics_reports_organization_period ON analytics_reports (organization_id, period_id)');
        $this->addSql('CREATE INDEX idx_analytics_reports_board_id ON analytics_reports (board_id)');
        $this->addSql('CREATE INDEX idx_analytics_reports_status ON analytics_reports (status)');
        $this->addSql('CREATE INDEX idx_analytics_reports_status_period ON analytics_reports (status, period_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_analytics_reports_org_board_period ON analytics_reports (organization_id, board_id, period_id)');
        $this->addSql('ALTER TABLE analytics_aggregated_data ADD CONSTRAINT FK_B846BFD1A952D583 FOREIGN KEY (metric_id) REFERENCES analytics_metrics (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_aggregated_data ADD CONSTRAINT FK_B846BFD1E7EC5785 FOREIGN KEY (board_id) REFERENCES analytics_boards (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_aggregated_data ADD CONSTRAINT FK_B846BFD14BD2A4C0 FOREIGN KEY (report_id) REFERENCES analytics_reports (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_aggregated_data ADD CONSTRAINT FK_B846BFD1EC8B7ADE FOREIGN KEY (period_id) REFERENCES analytics_periods (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_aggregated_data ADD CONSTRAINT FK_B846BFD132C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_audit_log ADD CONSTRAINT FK_98D0696FA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_board_version_metrics ADD CONSTRAINT FK_B5260707E7B2F3B9 FOREIGN KEY (board_version_id) REFERENCES analytics_board_versions (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_board_version_metrics ADD CONSTRAINT FK_B5260707A952D583 FOREIGN KEY (metric_id) REFERENCES analytics_metrics (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_board_versions ADD CONSTRAINT FK_FC29E3DBE7EC5785 FOREIGN KEY (board_id) REFERENCES analytics_boards (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_organization_boards ADD CONSTRAINT FK_FA00D52A32C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_organization_boards ADD CONSTRAINT FK_FA00D52AE7EC5785 FOREIGN KEY (board_id) REFERENCES analytics_boards (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_report_values ADD CONSTRAINT FK_7B57B5BB4BD2A4C0 FOREIGN KEY (report_id) REFERENCES analytics_reports (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_report_values ADD CONSTRAINT FK_7B57B5BB7112C4DC FOREIGN KEY (board_version_metric_id) REFERENCES analytics_board_version_metrics (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_report_values ADD CONSTRAINT FK_7B57B5BBDE12AB56 FOREIGN KEY (created_by) REFERENCES "user" (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_reports ADD CONSTRAINT FK_5BBD2BBB32C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_reports ADD CONSTRAINT FK_5BBD2BBBE7EC5785 FOREIGN KEY (board_id) REFERENCES analytics_boards (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_reports ADD CONSTRAINT FK_5BBD2BBBE7B2F3B9 FOREIGN KEY (board_version_id) REFERENCES analytics_board_versions (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_reports ADD CONSTRAINT FK_5BBD2BBBEC8B7ADE FOREIGN KEY (period_id) REFERENCES analytics_periods (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_reports ADD CONSTRAINT FK_5BBD2BBBDE12AB56 FOREIGN KEY (created_by) REFERENCES "user" (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_reports ADD CONSTRAINT FK_5BBD2BBB4EA3CB3D FOREIGN KEY (approved_by) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE analytics_aggregated_data DROP CONSTRAINT FK_B846BFD1A952D583');
        $this->addSql('ALTER TABLE analytics_aggregated_data DROP CONSTRAINT FK_B846BFD1E7EC5785');
        $this->addSql('ALTER TABLE analytics_aggregated_data DROP CONSTRAINT FK_B846BFD14BD2A4C0');
        $this->addSql('ALTER TABLE analytics_aggregated_data DROP CONSTRAINT FK_B846BFD1EC8B7ADE');
        $this->addSql('ALTER TABLE analytics_aggregated_data DROP CONSTRAINT FK_B846BFD132C8A3DE');
        $this->addSql('ALTER TABLE analytics_audit_log DROP CONSTRAINT FK_98D0696FA76ED395');
        $this->addSql('ALTER TABLE analytics_board_version_metrics DROP CONSTRAINT FK_B5260707E7B2F3B9');
        $this->addSql('ALTER TABLE analytics_board_version_metrics DROP CONSTRAINT FK_B5260707A952D583');
        $this->addSql('ALTER TABLE analytics_board_versions DROP CONSTRAINT FK_FC29E3DBE7EC5785');
        $this->addSql('ALTER TABLE analytics_organization_boards DROP CONSTRAINT FK_FA00D52A32C8A3DE');
        $this->addSql('ALTER TABLE analytics_organization_boards DROP CONSTRAINT FK_FA00D52AE7EC5785');
        $this->addSql('ALTER TABLE analytics_report_values DROP CONSTRAINT FK_7B57B5BB4BD2A4C0');
        $this->addSql('ALTER TABLE analytics_report_values DROP CONSTRAINT FK_7B57B5BB7112C4DC');
        $this->addSql('ALTER TABLE analytics_report_values DROP CONSTRAINT FK_7B57B5BBDE12AB56');
        $this->addSql('ALTER TABLE analytics_reports DROP CONSTRAINT FK_5BBD2BBB32C8A3DE');
        $this->addSql('ALTER TABLE analytics_reports DROP CONSTRAINT FK_5BBD2BBBE7EC5785');
        $this->addSql('ALTER TABLE analytics_reports DROP CONSTRAINT FK_5BBD2BBBE7B2F3B9');
        $this->addSql('ALTER TABLE analytics_reports DROP CONSTRAINT FK_5BBD2BBBEC8B7ADE');
        $this->addSql('ALTER TABLE analytics_reports DROP CONSTRAINT FK_5BBD2BBBDE12AB56');
        $this->addSql('ALTER TABLE analytics_reports DROP CONSTRAINT FK_5BBD2BBB4EA3CB3D');
        $this->addSql('DROP TABLE analytics_aggregated_data');
        $this->addSql('DROP TABLE analytics_audit_log');
        $this->addSql('DROP TABLE analytics_board_version_metrics');
        $this->addSql('DROP TABLE analytics_board_versions');
        $this->addSql('DROP TABLE analytics_boards');
        $this->addSql('DROP TABLE analytics_metrics');
        $this->addSql('DROP TABLE analytics_organization_boards');
        $this->addSql('DROP TABLE analytics_periods');
        $this->addSql('DROP TABLE analytics_report_values');
        $this->addSql('DROP TABLE analytics_reports');
    }
}
