<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260423063823 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE document_comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, document_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_301BF4B0C33F7837 ON document_comment (document_id)');
        $this->addSql('CREATE INDEX IDX_301BF4B0F675F31B ON document_comment (author_id)');
        $this->addSql('CREATE TABLE document_comment_file (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, storage_key VARCHAR(500) DEFAULT NULL, filename VARCHAR(255) DEFAULT NULL, content_type VARCHAR(100) DEFAULT NULL, size_bytes INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, comment_id INT NOT NULL, author_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_74CB58DF8697D13 ON document_comment_file (comment_id)');
        $this->addSql('CREATE INDEX IDX_74CB58DF675F31B ON document_comment_file (author_id)');
        $this->addSql('ALTER TABLE document_comment ADD CONSTRAINT FK_301BF4B0C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document_comment ADD CONSTRAINT FK_301BF4B0F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document_comment_file ADD CONSTRAINT FK_74CB58DF8697D13 FOREIGN KEY (comment_id) REFERENCES document_comment (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document_comment_file ADD CONSTRAINT FK_74CB58DF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE document_comment DROP CONSTRAINT FK_301BF4B0C33F7837');
        $this->addSql('ALTER TABLE document_comment DROP CONSTRAINT FK_301BF4B0F675F31B');
        $this->addSql('ALTER TABLE document_comment_file DROP CONSTRAINT FK_74CB58DF8697D13');
        $this->addSql('ALTER TABLE document_comment_file DROP CONSTRAINT FK_74CB58DF675F31B');
        $this->addSql('DROP TABLE document_comment');
        $this->addSql('DROP TABLE document_comment_file');
    }
}
