<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260730054149 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE analytics_tko_vehicle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, license_number VARCHAR(64) NOT NULL, model VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, volume NUMERIC(14, 3) DEFAULT NULL, compaction_ratio NUMERIC(14, 3) DEFAULT NULL, fuel_consumption_norm NUMERIC(14, 3) DEFAULT NULL, planned_write_off DATE DEFAULT NULL, status VARCHAR(20) DEFAULT \'active\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organization_id INT DEFAULT NULL, driver_id INT DEFAULT NULL, created_by INT DEFAULT NULL, updated_by INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A1EFEC10DE12AB56 ON analytics_tko_vehicle (created_by)');
        $this->addSql('CREATE INDEX IDX_A1EFEC1016FE72E1 ON analytics_tko_vehicle (updated_by)');
        $this->addSql('CREATE INDEX idx_analytics_tko_vehicle_organization_id ON analytics_tko_vehicle (organization_id)');
        $this->addSql('CREATE INDEX idx_analytics_tko_vehicle_driver_id ON analytics_tko_vehicle (driver_id)');
        $this->addSql('CREATE INDEX idx_analytics_tko_vehicle_status ON analytics_tko_vehicle (status)');
        $this->addSql('CREATE UNIQUE INDEX uniq_analytics_tko_vehicle_license_number ON analytics_tko_vehicle (license_number)');
        $this->addSql('CREATE TABLE analytics_tko_vehicle_attachment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) NOT NULL, storage_key VARCHAR(500) NOT NULL, content_type VARCHAR(100) NOT NULL, size_bytes INT NOT NULL, context VARCHAR(20) DEFAULT \'vehicle\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, vehicle_id INT NOT NULL, author_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1A54A9DFF675F31B ON analytics_tko_vehicle_attachment (author_id)');
        $this->addSql('CREATE INDEX idx_analytics_tko_vehicle_attachment_vehicle_id ON analytics_tko_vehicle_attachment (vehicle_id)');
        $this->addSql('CREATE INDEX idx_analytics_tko_vehicle_attachment_context ON analytics_tko_vehicle_attachment (context)');
        $this->addSql('CREATE TABLE analytics_tko_vehicle_trip (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, trip_date DATE NOT NULL, trip_number INT NOT NULL, weight NUMERIC(14, 3) NOT NULL, vehicle_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_analytics_tko_vehicle_trip_trip_date ON analytics_tko_vehicle_trip (trip_date)');
        $this->addSql('CREATE INDEX idx_analytics_tko_vehicle_trip_vehicle_id ON analytics_tko_vehicle_trip (vehicle_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_analytics_tko_vehicle_trip ON analytics_tko_vehicle_trip (vehicle_id, trip_date, trip_number)');
        $this->addSql('ALTER TABLE analytics_tko_vehicle ADD CONSTRAINT FK_A1EFEC1032C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_tko_vehicle ADD CONSTRAINT FK_A1EFEC10C3423909 FOREIGN KEY (driver_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_tko_vehicle ADD CONSTRAINT FK_A1EFEC10DE12AB56 FOREIGN KEY (created_by) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_tko_vehicle ADD CONSTRAINT FK_A1EFEC1016FE72E1 FOREIGN KEY (updated_by) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_tko_vehicle_attachment ADD CONSTRAINT FK_1A54A9DF545317D1 FOREIGN KEY (vehicle_id) REFERENCES analytics_tko_vehicle (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_tko_vehicle_attachment ADD CONSTRAINT FK_1A54A9DFF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_tko_vehicle_trip ADD CONSTRAINT FK_C298F617545317D1 FOREIGN KEY (vehicle_id) REFERENCES analytics_tko_vehicle (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE analytics_tko_vehicle DROP CONSTRAINT FK_A1EFEC1032C8A3DE');
        $this->addSql('ALTER TABLE analytics_tko_vehicle DROP CONSTRAINT FK_A1EFEC10C3423909');
        $this->addSql('ALTER TABLE analytics_tko_vehicle DROP CONSTRAINT FK_A1EFEC10DE12AB56');
        $this->addSql('ALTER TABLE analytics_tko_vehicle DROP CONSTRAINT FK_A1EFEC1016FE72E1');
        $this->addSql('ALTER TABLE analytics_tko_vehicle_attachment DROP CONSTRAINT FK_1A54A9DF545317D1');
        $this->addSql('ALTER TABLE analytics_tko_vehicle_attachment DROP CONSTRAINT FK_1A54A9DFF675F31B');
        $this->addSql('ALTER TABLE analytics_tko_vehicle_trip DROP CONSTRAINT FK_C298F617545317D1');
        $this->addSql('DROP TABLE analytics_tko_vehicle');
        $this->addSql('DROP TABLE analytics_tko_vehicle_attachment');
        $this->addSql('DROP TABLE analytics_tko_vehicle_trip');
    }
}
