<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260821084749 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE purchase_approval_stage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position SMALLINT NOT NULL, title VARCHAR(255) DEFAULT NULL, purpose VARCHAR(30) NOT NULL, allows_reject BOOLEAN DEFAULT true NOT NULL, status VARCHAR(30) DEFAULT \'PENDING\' NOT NULL, candidate_role_code VARCHAR(50) DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, purchase_request_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7FC3A3D64E4DEF6F ON purchase_approval_stage (purchase_request_id)');
        $this->addSql('CREATE INDEX IDX_7FC3A3D64E4DEF6F7B00651C ON purchase_approval_stage (purchase_request_id, status)');
        $this->addSql('CREATE UNIQUE INDEX uniq_purchase_approval_stage_position ON purchase_approval_stage (purchase_request_id, position)');
        $this->addSql('CREATE TABLE purchase_approval_task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position SMALLINT NOT NULL, assignment_type VARCHAR(30) NOT NULL, role_code VARCHAR(50) DEFAULT NULL, role_name VARCHAR(100) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, requires_file_type VARCHAR(30) DEFAULT NULL, decision VARCHAR(20) DEFAULT \'PENDING\' NOT NULL, decided_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, stage_id INT NOT NULL, assignee_user_id INT DEFAULT NULL, decided_by_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_50BC78D52298D193 ON purchase_approval_task (stage_id)');
        $this->addSql('CREATE INDEX IDX_50BC78D5BA8D7F59 ON purchase_approval_task (assignee_user_id)');
        $this->addSql('CREATE INDEX IDX_50BC78D5E26B496B ON purchase_approval_task (decided_by_id)');
        $this->addSql('CREATE INDEX IDX_50BC78D5B03A8386 ON purchase_approval_task (created_by_id)');
        $this->addSql('CREATE INDEX IDX_50BC78D52298D193462CE4F5 ON purchase_approval_task (stage_id, position)');
        $this->addSql('CREATE INDEX IDX_50BC78D5BA8D7F5984ACBE48 ON purchase_approval_task (assignee_user_id, decision)');
        $this->addSql('CREATE INDEX IDX_50BC78D5C9AA420C84ACBE48 ON purchase_approval_task (role_code, decision)');
        $this->addSql('CREATE TABLE purchase_approver (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_purchase_approver_user ON purchase_approver (user_id)');
        $this->addSql('CREATE TABLE purchase_approver_role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role_code VARCHAR(50) NOT NULL, approver_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_98386E62BB23766C ON purchase_approver_role (approver_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_purchase_approver_role ON purchase_approver_role (approver_id, role_code)');
        $this->addSql('CREATE TABLE purchase_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, image_key VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_purchase_category_name ON purchase_category (name)');
        $this->addSql('CREATE TABLE purchase_category_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, image_key VARCHAR(255) DEFAULT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4292E64612469DE2 ON purchase_category_item (category_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_purchase_category_item ON purchase_category_item (category_id, name)');
        $this->addSql('CREATE TABLE purchase_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, law VARCHAR(20) DEFAULT NULL, method VARCHAR(30) DEFAULT NULL, technical_spec TEXT DEFAULT NULL, supplier VARCHAR(255) DEFAULT NULL, status VARCHAR(50) NOT NULL, created_as VARCHAR(20) DEFAULT \'STANDARD\' NOT NULL, priority VARCHAR(20) DEFAULT \'NORMAL\' NOT NULL, applied_route_template_name VARCHAR(255) DEFAULT NULL, due_date DATE DEFAULT NULL, version INT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organization_id INT NOT NULL, created_by_id INT DEFAULT NULL, executor_id INT DEFAULT NULL, category_id INT DEFAULT NULL, route_template_id INT DEFAULT NULL, applied_route_template_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_204D45E632C8A3DE ON purchase_request (organization_id)');
        $this->addSql('CREATE INDEX IDX_204D45E6B03A8386 ON purchase_request (created_by_id)');
        $this->addSql('CREATE INDEX IDX_204D45E68ABD09BB ON purchase_request (executor_id)');
        $this->addSql('CREATE INDEX IDX_204D45E612469DE2 ON purchase_request (category_id)');
        $this->addSql('CREATE INDEX IDX_204D45E63BBA0FA9 ON purchase_request (route_template_id)');
        $this->addSql('CREATE INDEX IDX_204D45E68E2784AF ON purchase_request (applied_route_template_id)');
        $this->addSql('CREATE INDEX IDX_204D45E632C8A3DE7B00651C ON purchase_request (organization_id, status)');
        $this->addSql('CREATE INDEX IDX_204D45E67B00651C ON purchase_request (status)');
        $this->addSql('CREATE INDEX IDX_204D45E68B8E8428 ON purchase_request (created_at)');
        $this->addSql('CREATE TABLE purchase_request_comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, purchase_request_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C1B7F39F4E4DEF6F ON purchase_request_comment (purchase_request_id)');
        $this->addSql('CREATE INDEX IDX_C1B7F39FF675F31B ON purchase_request_comment (author_id)');
        $this->addSql('CREATE TABLE purchase_request_file (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, storage_key VARCHAR(255) NOT NULL, original_name VARCHAR(255) NOT NULL, type VARCHAR(30) DEFAULT \'OTHER\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, purchase_request_id INT NOT NULL, uploaded_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3722E64A4E4DEF6F ON purchase_request_file (purchase_request_id)');
        $this->addSql('CREATE INDEX IDX_3722E64AA2B28FE8 ON purchase_request_file (uploaded_by_id)');
        $this->addSql('CREATE TABLE purchase_request_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(30) DEFAULT NULL, from_status VARCHAR(50) DEFAULT NULL, to_status VARCHAR(50) NOT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, purchase_request_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7279D1B84E4DEF6F ON purchase_request_history (purchase_request_id)');
        $this->addSql('CREATE INDEX IDX_7279D1B8A76ED395 ON purchase_request_history (user_id)');
        $this->addSql('CREATE TABLE purchase_request_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, quantity NUMERIC(12, 3) NOT NULL, unit VARCHAR(20) NOT NULL, estimated_price NUMERIC(12, 2) NOT NULL, position INT NOT NULL, excluded BOOLEAN DEFAULT false NOT NULL, approved_quantity NUMERIC(12, 3) DEFAULT NULL, purchase_request_id INT NOT NULL, category_item_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A4A6F5444E4DEF6F ON purchase_request_item (purchase_request_id)');
        $this->addSql('CREATE INDEX IDX_A4A6F544D5B71220 ON purchase_request_item (category_item_id)');
        $this->addSql('CREATE TABLE purchase_route_default (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, kind VARCHAR(20) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, template_id INT NOT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CD1FE4585DA0FB8 ON purchase_route_default (template_id)');
        $this->addSql('CREATE INDEX IDX_CD1FE458896DBBDE ON purchase_route_default (updated_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_purchase_route_default_kind ON purchase_route_default (kind)');
        $this->addSql('CREATE TABLE purchase_route_template (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, allowed_kinds JSON NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, sort_order SMALLINT DEFAULT 0 NOT NULL, version INT DEFAULT 1 NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E49248E4896DBBDE ON purchase_route_template (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_E49248E41B5771DD45AFA4EA ON purchase_route_template (is_active, sort_order)');
        $this->addSql('CREATE UNIQUE INDEX uniq_purchase_route_template_code ON purchase_route_template (code)');
        $this->addSql('CREATE TABLE purchase_route_template_stage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position SMALLINT NOT NULL, title VARCHAR(255) DEFAULT NULL, purpose VARCHAR(30) NOT NULL, allows_reject BOOLEAN DEFAULT true NOT NULL, template_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_14B064BA5DA0FB8 ON purchase_route_template_stage (template_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_purchase_route_template_stage_position ON purchase_route_template_stage (template_id, position)');
        $this->addSql('CREATE TABLE purchase_route_template_task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position SMALLINT NOT NULL, assignment_type VARCHAR(20) NOT NULL, role_code VARCHAR(50) DEFAULT NULL, candidate_role_code VARCHAR(50) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, requires_file_type VARCHAR(30) DEFAULT NULL, stage_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_482AE0852298D193 ON purchase_route_template_task (stage_id)');
        $this->addSql('CREATE INDEX IDX_482AE0852298D193462CE4F5 ON purchase_route_template_task (stage_id, position)');
        $this->addSql('ALTER TABLE purchase_approval_stage ADD CONSTRAINT FK_7FC3A3D64E4DEF6F FOREIGN KEY (purchase_request_id) REFERENCES purchase_request (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_approval_task ADD CONSTRAINT FK_50BC78D52298D193 FOREIGN KEY (stage_id) REFERENCES purchase_approval_stage (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_approval_task ADD CONSTRAINT FK_50BC78D5BA8D7F59 FOREIGN KEY (assignee_user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_approval_task ADD CONSTRAINT FK_50BC78D5E26B496B FOREIGN KEY (decided_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_approval_task ADD CONSTRAINT FK_50BC78D5B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_approver ADD CONSTRAINT FK_A1417E1EA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_approver_role ADD CONSTRAINT FK_98386E62BB23766C FOREIGN KEY (approver_id) REFERENCES purchase_approver (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_category_item ADD CONSTRAINT FK_4292E64612469DE2 FOREIGN KEY (category_id) REFERENCES purchase_category (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request ADD CONSTRAINT FK_204D45E632C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request ADD CONSTRAINT FK_204D45E6B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request ADD CONSTRAINT FK_204D45E68ABD09BB FOREIGN KEY (executor_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request ADD CONSTRAINT FK_204D45E612469DE2 FOREIGN KEY (category_id) REFERENCES purchase_category (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request ADD CONSTRAINT FK_204D45E63BBA0FA9 FOREIGN KEY (route_template_id) REFERENCES purchase_route_template (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request ADD CONSTRAINT FK_204D45E68E2784AF FOREIGN KEY (applied_route_template_id) REFERENCES purchase_route_template (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request_comment ADD CONSTRAINT FK_C1B7F39F4E4DEF6F FOREIGN KEY (purchase_request_id) REFERENCES purchase_request (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request_comment ADD CONSTRAINT FK_C1B7F39FF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request_file ADD CONSTRAINT FK_3722E64A4E4DEF6F FOREIGN KEY (purchase_request_id) REFERENCES purchase_request (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request_file ADD CONSTRAINT FK_3722E64AA2B28FE8 FOREIGN KEY (uploaded_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request_history ADD CONSTRAINT FK_7279D1B84E4DEF6F FOREIGN KEY (purchase_request_id) REFERENCES purchase_request (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request_history ADD CONSTRAINT FK_7279D1B8A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request_item ADD CONSTRAINT FK_A4A6F5444E4DEF6F FOREIGN KEY (purchase_request_id) REFERENCES purchase_request (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request_item ADD CONSTRAINT FK_A4A6F544D5B71220 FOREIGN KEY (category_item_id) REFERENCES purchase_category_item (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_route_default ADD CONSTRAINT FK_CD1FE4585DA0FB8 FOREIGN KEY (template_id) REFERENCES purchase_route_template (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_route_default ADD CONSTRAINT FK_CD1FE458896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_route_template ADD CONSTRAINT FK_E49248E4896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_route_template_stage ADD CONSTRAINT FK_14B064BA5DA0FB8 FOREIGN KEY (template_id) REFERENCES purchase_route_template (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_route_template_task ADD CONSTRAINT FK_482AE0852298D193 FOREIGN KEY (stage_id) REFERENCES purchase_route_template_stage (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE purchase_approval_stage DROP CONSTRAINT FK_7FC3A3D64E4DEF6F');
        $this->addSql('ALTER TABLE purchase_approval_task DROP CONSTRAINT FK_50BC78D52298D193');
        $this->addSql('ALTER TABLE purchase_approval_task DROP CONSTRAINT FK_50BC78D5BA8D7F59');
        $this->addSql('ALTER TABLE purchase_approval_task DROP CONSTRAINT FK_50BC78D5E26B496B');
        $this->addSql('ALTER TABLE purchase_approval_task DROP CONSTRAINT FK_50BC78D5B03A8386');
        $this->addSql('ALTER TABLE purchase_approver DROP CONSTRAINT FK_A1417E1EA76ED395');
        $this->addSql('ALTER TABLE purchase_approver_role DROP CONSTRAINT FK_98386E62BB23766C');
        $this->addSql('ALTER TABLE purchase_category_item DROP CONSTRAINT FK_4292E64612469DE2');
        $this->addSql('ALTER TABLE purchase_request DROP CONSTRAINT FK_204D45E632C8A3DE');
        $this->addSql('ALTER TABLE purchase_request DROP CONSTRAINT FK_204D45E6B03A8386');
        $this->addSql('ALTER TABLE purchase_request DROP CONSTRAINT FK_204D45E68ABD09BB');
        $this->addSql('ALTER TABLE purchase_request DROP CONSTRAINT FK_204D45E612469DE2');
        $this->addSql('ALTER TABLE purchase_request DROP CONSTRAINT FK_204D45E63BBA0FA9');
        $this->addSql('ALTER TABLE purchase_request DROP CONSTRAINT FK_204D45E68E2784AF');
        $this->addSql('ALTER TABLE purchase_request_comment DROP CONSTRAINT FK_C1B7F39F4E4DEF6F');
        $this->addSql('ALTER TABLE purchase_request_comment DROP CONSTRAINT FK_C1B7F39FF675F31B');
        $this->addSql('ALTER TABLE purchase_request_file DROP CONSTRAINT FK_3722E64A4E4DEF6F');
        $this->addSql('ALTER TABLE purchase_request_file DROP CONSTRAINT FK_3722E64AA2B28FE8');
        $this->addSql('ALTER TABLE purchase_request_history DROP CONSTRAINT FK_7279D1B84E4DEF6F');
        $this->addSql('ALTER TABLE purchase_request_history DROP CONSTRAINT FK_7279D1B8A76ED395');
        $this->addSql('ALTER TABLE purchase_request_item DROP CONSTRAINT FK_A4A6F5444E4DEF6F');
        $this->addSql('ALTER TABLE purchase_request_item DROP CONSTRAINT FK_A4A6F544D5B71220');
        $this->addSql('ALTER TABLE purchase_route_default DROP CONSTRAINT FK_CD1FE4585DA0FB8');
        $this->addSql('ALTER TABLE purchase_route_default DROP CONSTRAINT FK_CD1FE458896DBBDE');
        $this->addSql('ALTER TABLE purchase_route_template DROP CONSTRAINT FK_E49248E4896DBBDE');
        $this->addSql('ALTER TABLE purchase_route_template_stage DROP CONSTRAINT FK_14B064BA5DA0FB8');
        $this->addSql('ALTER TABLE purchase_route_template_task DROP CONSTRAINT FK_482AE0852298D193');
        $this->addSql('DROP TABLE purchase_approval_stage');
        $this->addSql('DROP TABLE purchase_approval_task');
        $this->addSql('DROP TABLE purchase_approver');
        $this->addSql('DROP TABLE purchase_approver_role');
        $this->addSql('DROP TABLE purchase_category');
        $this->addSql('DROP TABLE purchase_category_item');
        $this->addSql('DROP TABLE purchase_request');
        $this->addSql('DROP TABLE purchase_request_comment');
        $this->addSql('DROP TABLE purchase_request_file');
        $this->addSql('DROP TABLE purchase_request_history');
        $this->addSql('DROP TABLE purchase_request_item');
        $this->addSql('DROP TABLE purchase_route_default');
        $this->addSql('DROP TABLE purchase_route_template');
        $this->addSql('DROP TABLE purchase_route_template_stage');
        $this->addSql('DROP TABLE purchase_route_template_task');
    }
}
