<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260717122013 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE document_signature (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, level VARCHAR(32) NOT NULL, document_hash VARCHAR(64) NOT NULL, signature_value TEXT DEFAULT NULL, algorithm VARCHAR(64) NOT NULL, signed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(255) DEFAULT NULL, document_id INT NOT NULL, signer_id INT NOT NULL, certificate_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BCB029E0C33F7837 ON document_signature (document_id)');
        $this->addSql('CREATE INDEX IDX_BCB029E09588C067 ON document_signature (signer_id)');
        $this->addSql('CREATE INDEX IDX_BCB029E099223FFD ON document_signature (certificate_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_document_signature_signer ON document_signature (document_id, signer_id)');
        $this->addSql('CREATE TABLE user_certificate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, serial_number VARCHAR(255) NOT NULL, subject_dn VARCHAR(255) NOT NULL, certificate_pem TEXT NOT NULL, valid_from TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, valid_to TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(32) DEFAULT \'active\' NOT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, revocation_reason VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, issued_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_888713DFD948EE2 ON user_certificate (serial_number)');
        $this->addSql('CREATE INDEX IDX_888713DFA76ED395 ON user_certificate (user_id)');
        $this->addSql('CREATE INDEX IDX_888713DF784BB717 ON user_certificate (issued_by_id)');
        $this->addSql('ALTER TABLE document_signature ADD CONSTRAINT FK_BCB029E0C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document_signature ADD CONSTRAINT FK_BCB029E09588C067 FOREIGN KEY (signer_id) REFERENCES "user" (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document_signature ADD CONSTRAINT FK_BCB029E099223FFD FOREIGN KEY (certificate_id) REFERENCES user_certificate (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_certificate ADD CONSTRAINT FK_888713DFA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_certificate ADD CONSTRAINT FK_888713DF784BB717 FOREIGN KEY (issued_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document ADD signature_level VARCHAR(32) DEFAULT NULL');
        $this->addSql('ALTER TABLE document ADD canonical_file VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE document ADD canonical_file_hash VARCHAR(64) DEFAULT NULL');
        $this->addSql('ALTER TABLE document ADD signed_form_file VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE document ADD verification_code VARCHAR(16) DEFAULT NULL');
        $this->addSql('ALTER TABLE document ADD sent_to_signing_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D8698A76E821C39F ON document (verification_code)');
        $this->addSql('ALTER TABLE document_user_recipient ADD signing_order INT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE document_signature DROP CONSTRAINT FK_BCB029E0C33F7837');
        $this->addSql('ALTER TABLE document_signature DROP CONSTRAINT FK_BCB029E09588C067');
        $this->addSql('ALTER TABLE document_signature DROP CONSTRAINT FK_BCB029E099223FFD');
        $this->addSql('ALTER TABLE user_certificate DROP CONSTRAINT FK_888713DFA76ED395');
        $this->addSql('ALTER TABLE user_certificate DROP CONSTRAINT FK_888713DF784BB717');
        $this->addSql('DROP TABLE document_signature');
        $this->addSql('DROP TABLE user_certificate');
        $this->addSql('DROP INDEX UNIQ_D8698A76E821C39F');
        $this->addSql('ALTER TABLE document DROP signature_level');
        $this->addSql('ALTER TABLE document DROP canonical_file');
        $this->addSql('ALTER TABLE document DROP canonical_file_hash');
        $this->addSql('ALTER TABLE document DROP signed_form_file');
        $this->addSql('ALTER TABLE document DROP verification_code');
        $this->addSql('ALTER TABLE document DROP sent_to_signing_at');
        $this->addSql('ALTER TABLE document_user_recipient DROP signing_order');
    }
}
