<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260614150237 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE kanban_card_activity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(40) NOT NULL, old_value TEXT DEFAULT NULL, new_value TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, card_id INT NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A438482C4ACC9A20 ON kanban_card_activity (card_id)');
        $this->addSql('CREATE INDEX IDX_A438482CA76ED395 ON kanban_card_activity (user_id)');
        $this->addSql('CREATE INDEX idx_card_activity_card_created ON kanban_card_activity (card_id, created_at)');
        $this->addSql('ALTER TABLE kanban_card_activity ADD CONSTRAINT FK_A438482C4ACC9A20 FOREIGN KEY (card_id) REFERENCES kanban_card (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kanban_card_activity ADD CONSTRAINT FK_A438482CA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE kanban_card_activity DROP CONSTRAINT FK_A438482C4ACC9A20');
        $this->addSql('ALTER TABLE kanban_card_activity DROP CONSTRAINT FK_A438482CA76ED395');
        $this->addSql('DROP TABLE kanban_card_activity');
    }
}
