<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260630105210 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE kanban_project_user_folder (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, position DOUBLE PRECISION DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6A1FA684A76ED395 ON kanban_project_user_folder (user_id)');
        $this->addSql('CREATE INDEX idx_folder_user_position ON kanban_project_user_folder (user_id, position)');
        $this->addSql('ALTER TABLE kanban_project_user_folder ADD CONSTRAINT FK_6A1FA684A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kanban_card ADD completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE kanban_card ADD completed_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE kanban_card ADD CONSTRAINT FK_B214048085ECDE76 FOREIGN KEY (completed_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_B214048085ECDE76 ON kanban_card (completed_by_id)');
        $this->addSql('ALTER TABLE kanban_project_user ADD position DOUBLE PRECISION DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE kanban_project_user ADD folder_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE kanban_project_user ADD CONSTRAINT FK_C264CF6A162CB942 FOREIGN KEY (folder_id) REFERENCES kanban_project_user_folder (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_C264CF6A162CB942 ON kanban_project_user (folder_id)');
        $this->addSql('CREATE INDEX idx_project_user_folder_position ON kanban_project_user (user_id, folder_id, position)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE kanban_project_user_folder DROP CONSTRAINT FK_6A1FA684A76ED395');
        $this->addSql('DROP TABLE kanban_project_user_folder');
        $this->addSql('ALTER TABLE kanban_card DROP CONSTRAINT FK_B214048085ECDE76');
        $this->addSql('DROP INDEX IDX_B214048085ECDE76');
        $this->addSql('ALTER TABLE kanban_card DROP completed_at');
        $this->addSql('ALTER TABLE kanban_card DROP completed_by_id');
        $this->addSql('ALTER TABLE kanban_project_user DROP CONSTRAINT FK_C264CF6A162CB942');
        $this->addSql('DROP INDEX IDX_C264CF6A162CB942');
        $this->addSql('DROP INDEX idx_project_user_folder_position');
        $this->addSql('ALTER TABLE kanban_project_user DROP position');
        $this->addSql('ALTER TABLE kanban_project_user DROP folder_id');
    }
}
