<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260809102537 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE purchase_approval_step (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position SMALLINT NOT NULL, approver_kind VARCHAR(30) NOT NULL, approver_role VARCHAR(50) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, requires_file_type VARCHAR(30) DEFAULT NULL, mandatory BOOLEAN DEFAULT false NOT NULL, decision VARCHAR(20) DEFAULT \'PENDING\' NOT NULL, decided_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, purchase_request_id INT NOT NULL, approver_user_id INT DEFAULT NULL, decided_by_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_417B5DCC4E4DEF6F ON purchase_approval_step (purchase_request_id)');
        $this->addSql('CREATE INDEX IDX_417B5DCC5EC7554A ON purchase_approval_step (approver_user_id)');
        $this->addSql('CREATE INDEX IDX_417B5DCCE26B496B ON purchase_approval_step (decided_by_id)');
        $this->addSql('CREATE INDEX IDX_417B5DCCB03A8386 ON purchase_approval_step (created_by_id)');
        $this->addSql('CREATE INDEX IDX_417B5DCC4E4DEF6F462CE4F5 ON purchase_approval_step (purchase_request_id, position)');
        $this->addSql('CREATE INDEX IDX_417B5DCC5EC7554A84ACBE48 ON purchase_approval_step (approver_user_id, decision)');
        $this->addSql('CREATE INDEX IDX_417B5DCC4E2AD77D84ACBE48 ON purchase_approval_step (approver_role, decision)');
        $this->addSql('CREATE TABLE purchase_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, responsible_user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2F8E0A93BDAD1998 ON purchase_category (responsible_user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_purchase_category_name ON purchase_category (name)');
        $this->addSql('CREATE TABLE purchase_category_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4292E64612469DE2 ON purchase_category_item (category_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_purchase_category_item ON purchase_category_item (category_id, name)');
        $this->addSql('CREATE TABLE purchase_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, law VARCHAR(20) DEFAULT NULL, method VARCHAR(30) DEFAULT NULL, justification TEXT DEFAULT NULL, technical_spec TEXT DEFAULT NULL, status VARCHAR(50) NOT NULL, created_as VARCHAR(20) DEFAULT \'STANDARD\' NOT NULL, priority VARCHAR(20) DEFAULT \'NORMAL\' NOT NULL, due_date DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organization_id INT NOT NULL, created_by_id INT DEFAULT NULL, executor_id INT DEFAULT NULL, category_id INT DEFAULT NULL, route_template_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_204D45E632C8A3DE ON purchase_request (organization_id)');
        $this->addSql('CREATE INDEX IDX_204D45E6B03A8386 ON purchase_request (created_by_id)');
        $this->addSql('CREATE INDEX IDX_204D45E68ABD09BB ON purchase_request (executor_id)');
        $this->addSql('CREATE INDEX IDX_204D45E612469DE2 ON purchase_request (category_id)');
        $this->addSql('CREATE INDEX IDX_204D45E63BBA0FA9 ON purchase_request (route_template_id)');
        $this->addSql('CREATE INDEX IDX_204D45E632C8A3DE7B00651C ON purchase_request (organization_id, status)');
        $this->addSql('CREATE INDEX IDX_204D45E67B00651C ON purchase_request (status)');
        $this->addSql('CREATE INDEX IDX_204D45E68B8E8428 ON purchase_request (created_at)');
        $this->addSql('CREATE TABLE purchase_request_comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, purchase_request_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C1B7F39F4E4DEF6F ON purchase_request_comment (purchase_request_id)');
        $this->addSql('CREATE INDEX IDX_C1B7F39FF675F31B ON purchase_request_comment (author_id)');
        $this->addSql('CREATE TABLE purchase_request_file (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, storage_key VARCHAR(255) NOT NULL, original_name VARCHAR(255) NOT NULL, type VARCHAR(30) DEFAULT \'OTHER\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, purchase_request_id INT NOT NULL, uploaded_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3722E64A4E4DEF6F ON purchase_request_file (purchase_request_id)');
        $this->addSql('CREATE INDEX IDX_3722E64AA2B28FE8 ON purchase_request_file (uploaded_by_id)');
        $this->addSql('CREATE TABLE purchase_request_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, from_status VARCHAR(50) DEFAULT NULL, to_status VARCHAR(50) NOT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, purchase_request_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7279D1B84E4DEF6F ON purchase_request_history (purchase_request_id)');
        $this->addSql('CREATE INDEX IDX_7279D1B8A76ED395 ON purchase_request_history (user_id)');
        $this->addSql('CREATE TABLE purchase_request_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, quantity NUMERIC(12, 3) NOT NULL, unit VARCHAR(20) NOT NULL, estimated_price NUMERIC(12, 2) NOT NULL, position INT NOT NULL, purchase_request_id INT NOT NULL, category_item_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A4A6F5444E4DEF6F ON purchase_request_item (purchase_request_id)');
        $this->addSql('CREATE INDEX IDX_A4A6F544D5B71220 ON purchase_request_item (category_item_id)');
        $this->addSql('CREATE TABLE purchase_route_template (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, is_default_for VARCHAR(20) DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E49248E4107417A04B1EFC02 ON purchase_route_template (is_default_for, active)');
        $this->addSql('CREATE TABLE purchase_route_template_step (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position SMALLINT NOT NULL, approver_kind VARCHAR(30) NOT NULL, approver_role VARCHAR(50) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, requires_file_type VARCHAR(30) DEFAULT NULL, template_id INT NOT NULL, approver_user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_59EDC59C5DA0FB8 ON purchase_route_template_step (template_id)');
        $this->addSql('CREATE INDEX IDX_59EDC59C5EC7554A ON purchase_route_template_step (approver_user_id)');
        $this->addSql('CREATE TABLE purchase_setting (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key VARCHAR(100) NOT NULL, value JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_purchase_setting_key ON purchase_setting (key)');
        $this->addSql('ALTER TABLE purchase_approval_step ADD CONSTRAINT FK_417B5DCC4E4DEF6F FOREIGN KEY (purchase_request_id) REFERENCES purchase_request (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_approval_step ADD CONSTRAINT FK_417B5DCC5EC7554A FOREIGN KEY (approver_user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_approval_step ADD CONSTRAINT FK_417B5DCCE26B496B FOREIGN KEY (decided_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_approval_step ADD CONSTRAINT FK_417B5DCCB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_category ADD CONSTRAINT FK_2F8E0A93BDAD1998 FOREIGN KEY (responsible_user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_category_item ADD CONSTRAINT FK_4292E64612469DE2 FOREIGN KEY (category_id) REFERENCES purchase_category (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request ADD CONSTRAINT FK_204D45E632C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request ADD CONSTRAINT FK_204D45E6B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request ADD CONSTRAINT FK_204D45E68ABD09BB FOREIGN KEY (executor_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request ADD CONSTRAINT FK_204D45E612469DE2 FOREIGN KEY (category_id) REFERENCES purchase_category (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request ADD CONSTRAINT FK_204D45E63BBA0FA9 FOREIGN KEY (route_template_id) REFERENCES purchase_route_template (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request_comment ADD CONSTRAINT FK_C1B7F39F4E4DEF6F FOREIGN KEY (purchase_request_id) REFERENCES purchase_request (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request_comment ADD CONSTRAINT FK_C1B7F39FF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request_file ADD CONSTRAINT FK_3722E64A4E4DEF6F FOREIGN KEY (purchase_request_id) REFERENCES purchase_request (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request_file ADD CONSTRAINT FK_3722E64AA2B28FE8 FOREIGN KEY (uploaded_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request_history ADD CONSTRAINT FK_7279D1B84E4DEF6F FOREIGN KEY (purchase_request_id) REFERENCES purchase_request (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request_history ADD CONSTRAINT FK_7279D1B8A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request_item ADD CONSTRAINT FK_A4A6F5444E4DEF6F FOREIGN KEY (purchase_request_id) REFERENCES purchase_request (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_request_item ADD CONSTRAINT FK_A4A6F544D5B71220 FOREIGN KEY (category_item_id) REFERENCES purchase_category_item (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_route_template_step ADD CONSTRAINT FK_59EDC59C5DA0FB8 FOREIGN KEY (template_id) REFERENCES purchase_route_template (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_route_template_step ADD CONSTRAINT FK_59EDC59C5EC7554A FOREIGN KEY (approver_user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE purchase_approval_step DROP CONSTRAINT FK_417B5DCC4E4DEF6F');
        $this->addSql('ALTER TABLE purchase_approval_step DROP CONSTRAINT FK_417B5DCC5EC7554A');
        $this->addSql('ALTER TABLE purchase_approval_step DROP CONSTRAINT FK_417B5DCCE26B496B');
        $this->addSql('ALTER TABLE purchase_approval_step DROP CONSTRAINT FK_417B5DCCB03A8386');
        $this->addSql('ALTER TABLE purchase_category DROP CONSTRAINT FK_2F8E0A93BDAD1998');
        $this->addSql('ALTER TABLE purchase_category_item DROP CONSTRAINT FK_4292E64612469DE2');
        $this->addSql('ALTER TABLE purchase_request DROP CONSTRAINT FK_204D45E632C8A3DE');
        $this->addSql('ALTER TABLE purchase_request DROP CONSTRAINT FK_204D45E6B03A8386');
        $this->addSql('ALTER TABLE purchase_request DROP CONSTRAINT FK_204D45E68ABD09BB');
        $this->addSql('ALTER TABLE purchase_request DROP CONSTRAINT FK_204D45E612469DE2');
        $this->addSql('ALTER TABLE purchase_request DROP CONSTRAINT FK_204D45E63BBA0FA9');
        $this->addSql('ALTER TABLE purchase_request_comment DROP CONSTRAINT FK_C1B7F39F4E4DEF6F');
        $this->addSql('ALTER TABLE purchase_request_comment DROP CONSTRAINT FK_C1B7F39FF675F31B');
        $this->addSql('ALTER TABLE purchase_request_file DROP CONSTRAINT FK_3722E64A4E4DEF6F');
        $this->addSql('ALTER TABLE purchase_request_file DROP CONSTRAINT FK_3722E64AA2B28FE8');
        $this->addSql('ALTER TABLE purchase_request_history DROP CONSTRAINT FK_7279D1B84E4DEF6F');
        $this->addSql('ALTER TABLE purchase_request_history DROP CONSTRAINT FK_7279D1B8A76ED395');
        $this->addSql('ALTER TABLE purchase_request_item DROP CONSTRAINT FK_A4A6F5444E4DEF6F');
        $this->addSql('ALTER TABLE purchase_request_item DROP CONSTRAINT FK_A4A6F544D5B71220');
        $this->addSql('ALTER TABLE purchase_route_template_step DROP CONSTRAINT FK_59EDC59C5DA0FB8');
        $this->addSql('ALTER TABLE purchase_route_template_step DROP CONSTRAINT FK_59EDC59C5EC7554A');
        $this->addSql('DROP TABLE purchase_approval_step');
        $this->addSql('DROP TABLE purchase_category');
        $this->addSql('DROP TABLE purchase_category_item');
        $this->addSql('DROP TABLE purchase_request');
        $this->addSql('DROP TABLE purchase_request_comment');
        $this->addSql('DROP TABLE purchase_request_file');
        $this->addSql('DROP TABLE purchase_request_history');
        $this->addSql('DROP TABLE purchase_request_item');
        $this->addSql('DROP TABLE purchase_route_template');
        $this->addSql('DROP TABLE purchase_route_template_step');
        $this->addSql('DROP TABLE purchase_setting');
    }
}
