<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260728162141 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE analytics_tko_vehicle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, license_number VARCHAR(64) NOT NULL, volume NUMERIC(14, 3) DEFAULT NULL, compaction_ratio NUMERIC(14, 3) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, polygon_id INT NOT NULL, organization_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_analytics_tko_vehicle_polygon_id ON analytics_tko_vehicle (polygon_id)');
        $this->addSql('CREATE INDEX idx_analytics_tko_vehicle_organization_id ON analytics_tko_vehicle (organization_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_analytics_tko_vehicle_license_number ON analytics_tko_vehicle (license_number)');
        $this->addSql('CREATE TABLE analytics_tko_vehicle_trip (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, trip_date DATE NOT NULL, trip_number INT NOT NULL, weight NUMERIC(14, 3) NOT NULL, vehicle_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_analytics_tko_vehicle_trip_trip_date ON analytics_tko_vehicle_trip (trip_date)');
        $this->addSql('CREATE INDEX idx_analytics_tko_vehicle_trip_vehicle_id ON analytics_tko_vehicle_trip (vehicle_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_analytics_tko_vehicle_trip ON analytics_tko_vehicle_trip (vehicle_id, trip_date, trip_number)');
        $this->addSql('ALTER TABLE analytics_tko_vehicle ADD CONSTRAINT FK_A1EFEC1024C7C0FB FOREIGN KEY (polygon_id) REFERENCES polygon (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_tko_vehicle ADD CONSTRAINT FK_A1EFEC1032C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE analytics_tko_vehicle_trip ADD CONSTRAINT FK_C298F617545317D1 FOREIGN KEY (vehicle_id) REFERENCES analytics_tko_vehicle (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE analytics_tko_vehicle DROP CONSTRAINT FK_A1EFEC1024C7C0FB');
        $this->addSql('ALTER TABLE analytics_tko_vehicle DROP CONSTRAINT FK_A1EFEC1032C8A3DE');
        $this->addSql('ALTER TABLE analytics_tko_vehicle_trip DROP CONSTRAINT FK_C298F617545317D1');
        $this->addSql('DROP TABLE analytics_tko_vehicle');
        $this->addSql('DROP TABLE analytics_tko_vehicle_trip');
    }
}
