<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260721101730 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE rest_game_score (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, game VARCHAR(50) NOT NULL, score INT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_59632C15A76ED395 ON rest_game_score (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_rest_game_score_user_game ON rest_game_score (user_id, game)');
        $this->addSql('ALTER TABLE rest_game_score ADD CONSTRAINT FK_59632C15A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE rest_game_score DROP CONSTRAINT FK_59632C15A76ED395');
        $this->addSql('DROP TABLE rest_game_score');
    }
}
