<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260227183058 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(50) DEFAULT NULL, deadline DATE DEFAULT NULL, original_file VARCHAR(255) DEFAULT NULL, updated_file VARCHAR(255) DEFAULT NULL, is_published BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, organization_creator_id INT NOT NULL, document_type_id INT NOT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D8698A7688799C49 ON document (organization_creator_id)');
        $this->addSql('CREATE INDEX IDX_D8698A7661232A4F ON document (document_type_id)');
        $this->addSql('CREATE INDEX IDX_D8698A76B03A8386 ON document (created_by_id)');
        $this->addSql('CREATE TABLE document_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(255) DEFAULT NULL, old_status VARCHAR(255) NOT NULL, new_status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, document_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_83D5D697C33F7837 ON document_history (document_id)');
        $this->addSql('CREATE INDEX IDX_83D5D697A76ED395 ON document_history (user_id)');
        $this->addSql('CREATE TABLE document_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE document_user_recipient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, document_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_12A983A1C33F7837 ON document_user_recipient (document_id)');
        $this->addSql('CREATE INDEX IDX_12A983A1A76ED395 ON document_user_recipient (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_document_user ON document_user_recipient (document_id, user_id)');
        $this->addSql('CREATE TABLE file (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, file_path VARCHAR(255) DEFAULT NULL, document_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8C9F3610C33F7837 ON file (document_id)');
        $this->addSql('CREATE TABLE kanban_attachment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) NOT NULL, storage_key VARCHAR(500) NOT NULL, content_type VARCHAR(100) NOT NULL, size_bytes INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, card_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_39C29C4F4ACC9A20 ON kanban_attachment (card_id)');
        $this->addSql('CREATE TABLE kanban_board (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AA902B95B03A8386 ON kanban_board (created_by_id)');
        $this->addSql('CREATE TABLE kanban_board_member (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(20) NOT NULL, board_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AA9C6FE4E7EC5785 ON kanban_board_member (board_id)');
        $this->addSql('CREATE INDEX IDX_AA9C6FE4A76ED395 ON kanban_board_member (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_board_member ON kanban_board_member (board_id, user_id)');
        $this->addSql('CREATE TABLE kanban_card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(500) NOT NULL, description TEXT DEFAULT NULL, position DOUBLE PRECISION NOT NULL, due_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, priority SMALLINT DEFAULT NULL, is_archived BOOLEAN DEFAULT false NOT NULL, border_color VARCHAR(20) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, column_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B2140480BE8E8ED5 ON kanban_card (column_id)');
        $this->addSql('CREATE TABLE kanban_card_label (kanban_card_id INT NOT NULL, kanban_label_id INT NOT NULL, PRIMARY KEY (kanban_card_id, kanban_label_id))');
        $this->addSql('CREATE INDEX IDX_760EE4DAF9C2CF7B ON kanban_card_label (kanban_card_id)');
        $this->addSql('CREATE INDEX IDX_760EE4DACFB3A910 ON kanban_card_label (kanban_label_id)');
        $this->addSql('CREATE TABLE kanban_card_assignee (card_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (card_id, user_id))');
        $this->addSql('CREATE INDEX IDX_74D1BD7A4ACC9A20 ON kanban_card_assignee (card_id)');
        $this->addSql('CREATE INDEX IDX_74D1BD7AA76ED395 ON kanban_card_assignee (user_id)');
        $this->addSql('CREATE TABLE kanban_card_comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, card_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B50809214ACC9A20 ON kanban_card_comment (card_id)');
        $this->addSql('CREATE INDEX IDX_B5080921F675F31B ON kanban_card_comment (author_id)');
        $this->addSql('CREATE TABLE kanban_checklist_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(500) NOT NULL, is_completed BOOLEAN DEFAULT false NOT NULL, position DOUBLE PRECISION NOT NULL, card_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_548D5BE54ACC9A20 ON kanban_checklist_item (card_id)');
        $this->addSql('CREATE TABLE kanban_column (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, header_color VARCHAR(30) DEFAULT \'bg-primary\' NOT NULL, position DOUBLE PRECISION NOT NULL, board_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_157CF286E7EC5785 ON kanban_column (board_id)');
        $this->addSql('CREATE TABLE kanban_label (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, color VARCHAR(30) NOT NULL, board_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FC61503AE7EC5785 ON kanban_label (board_id)');
        $this->addSql('CREATE TABLE organization (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, short_name VARCHAR(255) NOT NULL, full_name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, legal_address VARCHAR(255) DEFAULT NULL, actual_address VARCHAR(255) DEFAULT NULL, phone VARCHAR(100) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, parent_id INT DEFAULT NULL, discriminator VARCHAR(32) NOT NULL, inn VARCHAR(12) DEFAULT NULL, kpp VARCHAR(9) DEFAULT NULL, ogrn VARCHAR(15) DEFAULT NULL, registration_date DATE DEFAULT NULL, registration_organ VARCHAR(500) DEFAULT NULL, bank_name VARCHAR(255) DEFAULT NULL, bik VARCHAR(9) DEFAULT NULL, bank_account VARCHAR(20) DEFAULT NULL, tax_type VARCHAR(50) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C1EE637C727ACA70 ON organization (parent_id)');
        $this->addSql('CREATE TABLE role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, label VARCHAR(128) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_role_name ON role (name)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, lastname VARCHAR(50) NOT NULL, firstname VARCHAR(50) NOT NULL, patronymic VARCHAR(50) DEFAULT NULL, phone VARCHAR(30) DEFAULT NULL, birth_date DATE DEFAULT NULL, email VARCHAR(50) DEFAULT NULL, login VARCHAR(50) NOT NULL, password VARCHAR(255) NOT NULL, employee_status VARCHAR(50) DEFAULT \'AT_WORK\' NOT NULL, work_with_documents BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, organization_id INT NOT NULL, boss_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D93D64932C8A3DE ON "user" (organization_id)');
        $this->addSql('CREATE INDEX IDX_8D93D649261FB672 ON "user" (boss_id)');
        $this->addSql('CREATE INDEX IDX_8D93D649B03A8386 ON "user" (created_by_id)');
        $this->addSql('CREATE INDEX IDX_8D93D649896DBBDE ON "user" (updated_by_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_LOGIN ON "user" (login)');
        $this->addSql('CREATE TABLE user_role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, role_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2DE8C6A3A76ED395 ON user_role (user_id)');
        $this->addSql('CREATE INDEX IDX_2DE8C6A3D60322AC ON user_role (role_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_role ON user_role (user_id, role_id)');
        $this->addSql('CREATE TABLE worker (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, profession VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A7688799C49 FOREIGN KEY (organization_creator_id) REFERENCES organization (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A7661232A4F FOREIGN KEY (document_type_id) REFERENCES document_type (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document_history ADD CONSTRAINT FK_83D5D697C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document_history ADD CONSTRAINT FK_83D5D697A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document_user_recipient ADD CONSTRAINT FK_12A983A1C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document_user_recipient ADD CONSTRAINT FK_12A983A1A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE file ADD CONSTRAINT FK_8C9F3610C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kanban_attachment ADD CONSTRAINT FK_39C29C4F4ACC9A20 FOREIGN KEY (card_id) REFERENCES kanban_card (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kanban_board ADD CONSTRAINT FK_AA902B95B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kanban_board_member ADD CONSTRAINT FK_AA9C6FE4E7EC5785 FOREIGN KEY (board_id) REFERENCES kanban_board (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kanban_board_member ADD CONSTRAINT FK_AA9C6FE4A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kanban_card ADD CONSTRAINT FK_B2140480BE8E8ED5 FOREIGN KEY (column_id) REFERENCES kanban_column (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kanban_card_label ADD CONSTRAINT FK_760EE4DAF9C2CF7B FOREIGN KEY (kanban_card_id) REFERENCES kanban_card (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE kanban_card_label ADD CONSTRAINT FK_760EE4DACFB3A910 FOREIGN KEY (kanban_label_id) REFERENCES kanban_label (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE kanban_card_assignee ADD CONSTRAINT FK_74D1BD7A4ACC9A20 FOREIGN KEY (card_id) REFERENCES kanban_card (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kanban_card_assignee ADD CONSTRAINT FK_74D1BD7AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kanban_card_comment ADD CONSTRAINT FK_B50809214ACC9A20 FOREIGN KEY (card_id) REFERENCES kanban_card (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kanban_card_comment ADD CONSTRAINT FK_B5080921F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kanban_checklist_item ADD CONSTRAINT FK_548D5BE54ACC9A20 FOREIGN KEY (card_id) REFERENCES kanban_card (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kanban_column ADD CONSTRAINT FK_157CF286E7EC5785 FOREIGN KEY (board_id) REFERENCES kanban_board (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kanban_label ADD CONSTRAINT FK_FC61503AE7EC5785 FOREIGN KEY (board_id) REFERENCES kanban_board (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE organization ADD CONSTRAINT FK_C1EE637C727ACA70 FOREIGN KEY (parent_id) REFERENCES organization (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D64932C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649261FB672 FOREIGN KEY (boss_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_role ADD CONSTRAINT FK_2DE8C6A3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_role ADD CONSTRAINT FK_2DE8C6A3D60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A7688799C49');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A7661232A4F');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A76B03A8386');
        $this->addSql('ALTER TABLE document_history DROP CONSTRAINT FK_83D5D697C33F7837');
        $this->addSql('ALTER TABLE document_history DROP CONSTRAINT FK_83D5D697A76ED395');
        $this->addSql('ALTER TABLE document_user_recipient DROP CONSTRAINT FK_12A983A1C33F7837');
        $this->addSql('ALTER TABLE document_user_recipient DROP CONSTRAINT FK_12A983A1A76ED395');
        $this->addSql('ALTER TABLE file DROP CONSTRAINT FK_8C9F3610C33F7837');
        $this->addSql('ALTER TABLE kanban_attachment DROP CONSTRAINT FK_39C29C4F4ACC9A20');
        $this->addSql('ALTER TABLE kanban_board DROP CONSTRAINT FK_AA902B95B03A8386');
        $this->addSql('ALTER TABLE kanban_board_member DROP CONSTRAINT FK_AA9C6FE4E7EC5785');
        $this->addSql('ALTER TABLE kanban_board_member DROP CONSTRAINT FK_AA9C6FE4A76ED395');
        $this->addSql('ALTER TABLE kanban_card DROP CONSTRAINT FK_B2140480BE8E8ED5');
        $this->addSql('ALTER TABLE kanban_card_label DROP CONSTRAINT FK_760EE4DAF9C2CF7B');
        $this->addSql('ALTER TABLE kanban_card_label DROP CONSTRAINT FK_760EE4DACFB3A910');
        $this->addSql('ALTER TABLE kanban_card_assignee DROP CONSTRAINT FK_74D1BD7A4ACC9A20');
        $this->addSql('ALTER TABLE kanban_card_assignee DROP CONSTRAINT FK_74D1BD7AA76ED395');
        $this->addSql('ALTER TABLE kanban_card_comment DROP CONSTRAINT FK_B50809214ACC9A20');
        $this->addSql('ALTER TABLE kanban_card_comment DROP CONSTRAINT FK_B5080921F675F31B');
        $this->addSql('ALTER TABLE kanban_checklist_item DROP CONSTRAINT FK_548D5BE54ACC9A20');
        $this->addSql('ALTER TABLE kanban_column DROP CONSTRAINT FK_157CF286E7EC5785');
        $this->addSql('ALTER TABLE kanban_label DROP CONSTRAINT FK_FC61503AE7EC5785');
        $this->addSql('ALTER TABLE organization DROP CONSTRAINT FK_C1EE637C727ACA70');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D64932C8A3DE');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649261FB672');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649B03A8386');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649896DBBDE');
        $this->addSql('ALTER TABLE user_role DROP CONSTRAINT FK_2DE8C6A3A76ED395');
        $this->addSql('ALTER TABLE user_role DROP CONSTRAINT FK_2DE8C6A3D60322AC');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE document_history');
        $this->addSql('DROP TABLE document_type');
        $this->addSql('DROP TABLE document_user_recipient');
        $this->addSql('DROP TABLE file');
        $this->addSql('DROP TABLE kanban_attachment');
        $this->addSql('DROP TABLE kanban_board');
        $this->addSql('DROP TABLE kanban_board_member');
        $this->addSql('DROP TABLE kanban_card');
        $this->addSql('DROP TABLE kanban_card_label');
        $this->addSql('DROP TABLE kanban_card_assignee');
        $this->addSql('DROP TABLE kanban_card_comment');
        $this->addSql('DROP TABLE kanban_checklist_item');
        $this->addSql('DROP TABLE kanban_column');
        $this->addSql('DROP TABLE kanban_label');
        $this->addSql('DROP TABLE organization');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_role');
        $this->addSql('DROP TABLE worker');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
