# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # directories
    private_upload_dir: '%env(resolve:PRIVATE_UPLOAD_DIR)%'

    # kanban uploads
    private_upload_kanban_dir: '%env(resolve:PRIVATE_UPLOAD_KANBAN_DIR)%'

    # documents
    private_upload_dir_documents_originals: '%env(resolve:PRIVATE_UPLOAD_DIR_DOCUMENTS_ORIGINALS)%'
    private_upload_dir_documents_updated: '%env(resolve:PRIVATE_UPLOAD_DIR_DOCUMENTS_UPDATED)%'
    private_upload_dir_documents_templates: '%env(resolve:PRIVATE_UPLOAD_DIR_DOCUMENTS_TEMPLATES)%'
    private_upload_dir_documents_comments: '%env(resolve:PRIVATE_UPLOAD_DIR_DOCUMENTS_COMMENTS)%'
    private_upload_dir_posts: '%env(resolve:PRIVATE_UPLOAD_DIR_POSTS)%'
    private_upload_dir_users: '%env(resolve:PRIVATE_UPLOAD_DIR_USERS)%'
    private_upload_dir_chats: '%env(resolve:PRIVATE_UPLOAD_DIR_CHATS)%'

    # onlyoffice url
    onlyoffice_document_server_url: '%env(resolve:ONLYOFFICE_DOCUMENT_SERVER_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\DataFixtures\:
        resource: '../src/DataFixtures/'
        tags: ['doctrine.fixture.orm']

    App\Service\Kanban\KanbanAttachmentService:
        arguments:
            $kanbanUploadDir: '%private_upload_kanban_dir%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
