<?php

namespace App\DataFixtures;

use App\Entity\Organization;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class OrganizationFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $organizationsData = [
            [
                'name' => 'ООО "ДонСтройМаш"',
                'description' => 'Основная строительная организация, специализирующаяся на производстве строительных материалов и машин',
                'address' => 'г. Ростов-на-Дону, ул. Строительная, д. 1',
                'phone' => '+7 (863) 123-45-67',
                'email' => 'info@donstroymash.ru',
                'parent_index' => null,
            ],
            [
                'name' => 'ООО "СтройКомплекс"',
                'description' => 'Комплексное строительное предприятие',
                'address' => 'г. Ростов-на-Дону, пр. Ленина, д. 50',
                'phone' => '+7 (863) 234-56-78',
                'email' => 'contact@stroykomplex.ru',
                'parent_index' => 0,
            ],
            [
                'name' => 'ООО "МашСтрой"',
                'description' => 'Производство строительной техники и оборудования',
                'address' => 'г. Ростов-на-Дону, ул. Промышленная, д. 25',
                'phone' => '+7 (863) 345-67-89',
                'email' => 'office@mashstroy.ru',
                'parent_index' => null,
            ],
            [
                'name' => 'ООО "СтройМатериалы"',
                'description' => 'Оптовая и розничная торговля строительными материалами',
                'address' => 'г. Ростов-на-Дону, ул. Торговая, д. 10',
                'phone' => '+7 (863) 456-78-90',
                'email' => 'sales@stroymaterialy.ru',
                'parent_index' => null,
            ],
            [
                'name' => 'ООО "СтройПроект"',
                'description' => 'Проектирование и архитектурное бюро',
                'address' => 'г. Ростов-на-Дону, ул. Архитекторов, д. 5',
                'phone' => '+7 (863) 567-89-01',
                'email' => 'project@stroyproekt.ru',
                'parent_index' => 0,
            ],
            [
                'name' => 'ООО "СтройКомплекс-Юг"',
                'description' => 'Южный филиал СтройКомплекса',
                'address' => 'г. Ростов-на-Дону, ул. Южная, д. 12',
                'phone' => '+7 (863) 234-56-79',
                'email' => 'yug@stroykomplex.ru',
                'parent_index' => 1,
            ],
            [
                'name' => 'ООО "СтройКомплекс-Склад"',
                'description' => 'Складская логистика СтройКомплекса',
                'address' => 'г. Ростов-на-Дону, промзона Восточная, д. 3',
                'phone' => '+7 (863) 234-56-80',
                'email' => 'sklad@stroykomplex.ru',
                'parent_index' => 1,
            ],
            [
                'name' => 'ООО "МашСтрой-Сервис"',
                'description' => 'Сервисное обслуживание техники МашСтрой',
                'address' => 'г. Ростов-на-Дону, ул. Сервисная, д. 8',
                'phone' => '+7 (863) 345-67-90',
                'email' => 'service@mashstroy.ru',
                'parent_index' => 2,
            ],
            [
                'name' => 'ООО "МашСтрой-Запчасти"',
                'description' => 'Производство запасных частей для строительной техники',
                'address' => 'г. Ростов-на-Дону, ул. Заводская, д. 15',
                'phone' => '+7 (863) 345-67-91',
                'email' => 'zapchasti@mashstroy.ru',
                'parent_index' => 2,
            ],
            [
                'name' => 'ООО "СтройМатериалы-Опт"',
                'description' => 'Оптовые поставки строительных материалов',
                'address' => 'г. Ростов-на-Дону, ул. Оптовая, д. 22',
                'phone' => '+7 (863) 456-78-91',
                'email' => 'opt@stroymaterialy.ru',
                'parent_index' => 3,
            ],
            [
                'name' => 'ООО "СтройМатериалы-Розница"',
                'description' => 'Розничная сеть строительных магазинов',
                'address' => 'г. Ростов-на-Дону, ул. Розничная, д. 7',
                'phone' => '+7 (863) 456-78-92',
                'email' => 'retail@stroymaterialy.ru',
                'parent_index' => 3,
            ],
            [
                'name' => 'ООО "СтройПроект-Архитектура"',
                'description' => 'Архитектурное проектирование',
                'address' => 'г. Ростов-на-Дону, ул. Черёмушкина, д. 18',
                'phone' => '+7 (863) 567-89-02',
                'email' => 'arch@stroyproekt.ru',
                'parent_index' => 4,
            ],
            [
                'name' => 'ООО "СтройПроект-Конструкции"',
                'description' => 'Конструкторский отдел',
                'address' => 'г. Ростов-на-Дону, ул. Конструкторская, д. 4',
                'phone' => '+7 (863) 567-89-03',
                'email' => 'design@stroyproekt.ru',
                'parent_index' => 4,
            ],
            [
                'name' => 'ООО "СтройКомплекс-Юг-Таганрог"',
                'description' => 'Представительство в Таганроге',
                'address' => 'г. Таганрог, ул. Петровская, д. 45',
                'phone' => '+7 (8634) 12-34-56',
                'email' => 'taganrog@stroykomplex.ru',
                'parent_index' => 6,
            ],
            [
                'name' => 'ООО "СтройКомплекс-Юг-Батайск"',
                'description' => 'Представительство в Батайске',
                'address' => 'г. Батайск, ул. Луначарского, д. 33',
                'phone' => '+7 (86354) 5-67-89',
                'email' => 'bataysk@stroykomplex.ru',
                'parent_index' => 6,
            ],
            [
                'name' => 'ООО "СтройКомплекс-Склад-Север"',
                'description' => 'Северный складской комплекс',
                'address' => 'г. Ростов-на-Дону, промзона Северная, д. 1',
                'phone' => '+7 (863) 234-56-81',
                'email' => 'sklad-north@stroykomplex.ru',
                'parent_index' => 7,
            ],
            [
                'name' => 'ООО "МашСтрой-Сервис-Ростов"',
                'description' => 'Ростовский сервисный центр',
                'address' => 'г. Ростов-на-Дону, ул. Малиновского, д. 56',
                'phone' => '+7 (863) 345-67-92',
                'email' => 'service-rnd@mashstroy.ru',
                'parent_index' => 8,
            ],
            [
                'name' => 'ООО "МашСтрой-Сервис-Краснодар"',
                'description' => 'Краснодарский сервисный центр',
                'address' => 'г. Краснодар, ул. Красная, д. 120',
                'phone' => '+7 (861) 234-56-78',
                'email' => 'service-krd@mashstroy.ru',
                'parent_index' => 8,
            ],
            [
                'name' => 'ООО "МашСтрой-Запчасти-Цех1"',
                'description' => 'Цех производства запчастей №1',
                'address' => 'г. Ростов-на-Дону, промзона Западная, д. 9',
                'phone' => '+7 (863) 345-67-93',
                'email' => 'ceh1@mashstroy.ru',
                'parent_index' => 9,
            ],
            [
                'name' => 'ООО "СтройМатериалы-Опт-Регион"',
                'description' => 'Региональные оптовые поставки',
                'address' => 'г. Ростов-на-Дону, ул. Региональная, д. 88',
                'phone' => '+7 (863) 456-78-93',
                'email' => 'region@stroymaterialy.ru',
                'parent_index' => 10,
            ],
            [
                'name' => 'ООО "СтройМатериалы-Розница-Магазин1"',
                'description' => 'Строительный гипермаркет №1',
                'address' => 'г. Ростов-на-Дону, пр. Космонавтов, д. 2',
                'phone' => '+7 (863) 456-78-94',
                'email' => 'store1@stroymaterialy.ru',
                'parent_index' => 11,
            ],
            [
                'name' => 'ООО "СтройМатериалы-Розница-Магазин2"',
                'description' => 'Строительный гипермаркет №2',
                'address' => 'г. Ростов-на-Дону, ул. Пойменная, д. 1',
                'phone' => '+7 (863) 456-78-95',
                'email' => 'store2@stroymaterialy.ru',
                'parent_index' => 11,
            ],
            [
                'name' => 'ООО "СтройПроект-Архитектура-Жилые"',
                'description' => 'Проектирование жилых зданий',
                'address' => 'г. Ростов-на-Дону, ул. Пушкинская, д. 100',
                'phone' => '+7 (863) 567-89-04',
                'email' => 'zhil@stroyproekt.ru',
                'parent_index' => 12,
            ],
            [
                'name' => 'ООО "СтройПроект-Архитектура-Пром"',
                'description' => 'Проектирование промышленных объектов',
                'address' => 'г. Ростов-на-Дону, ул. Портовая, д. 34',
                'phone' => '+7 (863) 567-89-05',
                'email' => 'prom@stroyproekt.ru',
                'parent_index' => 12,
            ],
            [
                'name' => 'ООО "СтройКомплекс-Юг-Таганрог-Участок"',
                'description' => 'Строительный участок в Таганроге',
                'address' => 'г. Таганрог, ул. Чехова, д. 78',
                'phone' => '+7 (8634) 12-34-57',
                'email' => 'uchastok@stroykomplex-taganrog.ru',
                'parent_index' => 14,
            ],
            [
                'name' => 'ООО "СтройКомплекс-Юг-Батайск-Склад"',
                'description' => 'Склад в Батайске',
                'address' => 'г. Батайск, ул. Куйбышева, д. 12',
                'phone' => '+7 (86354) 5-67-90',
                'email' => 'sklad@stroykomplex-bataysk.ru',
                'parent_index' => 15,
            ],
            [
                'name' => 'ООО "СтройКомплекс-Юг-Батайск-Офис"',
                'description' => 'Офис продаж в Батайске',
                'address' => 'г. Батайск, ул. Луначарского, д. 33А',
                'phone' => '+7 (86354) 5-67-91',
                'email' => 'office@stroykomplex-bataysk.ru',
                'parent_index' => 15,
            ],
            [
                'name' => 'ООО "СтройКомплекс-Склад-Север-ЗонаА"',
                'description' => 'Складская зона А северного комплекса',
                'address' => 'г. Ростов-на-Дону, промзона Северная, д. 1А',
                'phone' => '+7 (863) 234-56-82',
                'email' => 'zona-a@stroykomplex.ru',
                'parent_index' => 16,
            ],
            [
                'name' => 'ООО "СтройКомплекс-Склад-Север-ЗонаБ"',
                'description' => 'Складская зона Б северного комплекса',
                'address' => 'г. Ростов-на-Дону, промзона Северная, д. 1Б',
                'phone' => '+7 (863) 234-56-87',
                'email' => 'zona-b@stroykomplex.ru',
                'parent_index' => 16,
            ],
            [
                'name' => 'ООО "МашСтрой-Сервис-Ростов-Ремонт"',
                'description' => 'Цех капитального ремонта техники',
                'address' => 'г. Ростов-на-Дону, ул. Доватора, д. 144',
                'phone' => '+7 (863) 345-67-94',
                'email' => 'remont@mashstroy-rnd.ru',
                'parent_index' => 17,
            ],
            [
                'name' => 'ООО "МашСтрой-Запчасти-Цех1-Участок"',
                'description' => 'Участок токарных работ',
                'address' => 'г. Ростов-на-Дону, промзона Западная, д. 9А',
                'phone' => '+7 (863) 345-67-95',
                'email' => 'tokar@mashstroy.ru',
                'parent_index' => 19,
            ],
            [
                'name' => 'ООО "СтройПроект-Архитектура-Жилые-МКД"',
                'description' => 'Проектирование многоквартирных домов',
                'address' => 'г. Ростов-на-Дону, ул. Б. Садовая, д. 200',
                'phone' => '+7 (863) 567-89-06',
                'email' => 'mkd@stroyproekt.ru',
                'parent_index' => 23,
            ],
            [
                'name' => 'ООО "СтройПроект-Архитектура-Жилые-ИЖС"',
                'description' => 'Проектирование индивидуального жилищного строительства',
                'address' => 'г. Ростов-на-Дону, ул. Красноармейская, д. 50',
                'phone' => '+7 (863) 567-89-07',
                'email' => 'izhs@stroyproekt.ru',
                'parent_index' => 23,
            ],
            [
                'name' => 'ООО "СтройКомплекс-Юг-Таганрог-Участок-Объект1"',
                'description' => 'Строительный объект «Жилой комплекс Северный»',
                'address' => 'г. Таганрог, ул. Лизы Чайкиной, д. 5',
                'phone' => '+7 (8634) 12-34-58',
                'email' => 'object1@stroykomplex-taganrog.ru',
                'parent_index' => 25,
            ],
            [
                'name' => 'ООО "СтройКомплекс-Юг-Таганрог-Участок-Объект2"',
                'description' => 'Строительный объект «Бизнес-центр Петровский»',
                'address' => 'г. Таганрог, ул. Петровская, д. 78',
                'phone' => '+7 (8634) 12-34-62',
                'email' => 'object2@stroykomplex-taganrog.ru',
                'parent_index' => 25,
            ],
            [
                'name' => 'ООО "СтройКомплекс-Юг-Таганрог-Участок-Объект3"',
                'description' => 'Строительный объект «Складской комплекс Восточный»',
                'address' => 'г. Таганрог, промзона Восточная, д. 12',
                'phone' => '+7 (8634) 12-34-63',
                'email' => 'object3@stroykomplex-taganrog.ru',
                'parent_index' => 25,
            ],
            [
                'name' => 'ООО "СтройКомплекс-Склад-Север-ЗонаА-Сектор1"',
                'description' => 'Сектор 1 складской зоны А',
                'address' => 'г. Ростов-на-Дону, промзона Северная, д. 1А-1',
                'phone' => '+7 (863) 234-56-83',
                'email' => 'sector1@stroykomplex.ru',
                'parent_index' => 28,
            ],
            [
                'name' => 'ООО "СтройКомплекс-Склад-Север-ЗонаА-Сектор2"',
                'description' => 'Сектор 2 складской зоны А',
                'address' => 'г. Ростов-на-Дону, промзона Северная, д. 1А-2',
                'phone' => '+7 (863) 234-56-85',
                'email' => 'sector2@stroykomplex.ru',
                'parent_index' => 28,
            ],
            [
                'name' => 'ООО "СтройКомплекс-Склад-Север-ЗонаА-Сектор3"',
                'description' => 'Сектор 3 складской зоны А',
                'address' => 'г. Ростов-на-Дону, промзона Северная, д. 1А-3',
                'phone' => '+7 (863) 234-56-86',
                'email' => 'sector3@stroykomplex.ru',
                'parent_index' => 28,
            ],
            [
                'name' => 'ООО "МашСтрой-Сервис-Ростов-Ремонт-Двигатели"',
                'description' => 'Участок ремонта двигателей',
                'address' => 'г. Ростов-на-Дону, ул. Доватора, д. 144/1',
                'phone' => '+7 (863) 345-67-96',
                'email' => 'dvigateli@mashstroy-rnd.ru',
                'parent_index' => 30,
            ],
            [
                'name' => 'ООО "МашСтрой-Сервис-Ростов-Ремонт-Гидравлика"',
                'description' => 'Участок ремонта гидравлики',
                'address' => 'г. Ростов-на-Дону, ул. Доватора, д. 144/2',
                'phone' => '+7 (863) 345-67-98',
                'email' => 'gidravlika@mashstroy-rnd.ru',
                'parent_index' => 30,
            ],
            [
                'name' => 'ООО "МашСтрой-Сервис-Ростов-Ремонт-Ходовая"',
                'description' => 'Участок ремонта ходовой части',
                'address' => 'г. Ростов-на-Дону, ул. Доватора, д. 144/3',
                'phone' => '+7 (863) 345-67-99',
                'email' => 'hodovaya@mashstroy-rnd.ru',
                'parent_index' => 30,
            ],
            [
                'name' => 'ООО "СтройПроект-Архитектура-Жилые-МКД-Типовые"',
                'description' => 'Типовые проекты многоквартирных домов',
                'address' => 'г. Ростов-на-Дону, ул. Б. Садовая, д. 200, оф. 305',
                'phone' => '+7 (863) 567-89-08',
                'email' => 'tipovye@stroyproekt.ru',
                'parent_index' => 32,
            ],
            [
                'name' => 'ООО "СтройПроект-Архитектура-Жилые-МКД-Индивидуальные"',
                'description' => 'Индивидуальные проекты МКД',
                'address' => 'г. Ростов-на-Дону, ул. Б. Садовая, д. 200, оф. 306',
                'phone' => '+7 (863) 567-89-11',
                'email' => 'individual@stroyproekt.ru',
                'parent_index' => 32,
            ],
            [
                'name' => 'ООО "СтройКомплекс-Юг-Таганрог-Участок-Объект1-Этап1"',
                'description' => 'Этап 1 строительства ЖК Северный',
                'address' => 'г. Таганрог, ул. Лизы Чайкиной, д. 5, корп. 1',
                'phone' => '+7 (8634) 12-34-59',
                'email' => 'etap1@stroykomplex-taganrog.ru',
                'parent_index' => 34,
            ],
            [
                'name' => 'ООО "СтройКомплекс-Юг-Таганрог-Участок-Объект1-Этап1-СекцияА"',
                'description' => 'Секция А этапа 1 ЖК Северный (вложенность 7)',
                'address' => 'г. Таганрог, ул. Лизы Чайкиной, д. 5, корп. 1, секция А',
                'phone' => '+7 (8634) 12-34-60',
                'email' => 'sekciya-a@stroykomplex-taganrog.ru',
                'parent_index' => 44,
            ],
            [
                'name' => 'ООО "ДонСтройМаш-Логистика"',
                'description' => 'Логистическая служба холдинга',
                'address' => 'г. Ростов-на-Дону, ул. Транспортная, д. 20',
                'phone' => '+7 (863) 123-45-68',
                'email' => 'logistics@donstroymash.ru',
                'parent_index' => 0,
            ],
            [
                'name' => 'ООО "ДонСтройМаш-Кадры"',
                'description' => 'Центр управления персоналом',
                'address' => 'г. Ростов-на-Дону, ул. Строительная, д. 1, корп. 2',
                'phone' => '+7 (863) 123-45-69',
                'email' => 'hr@donstroymash.ru',
                'parent_index' => 0,
            ],
            [
                'name' => 'ООО "ДонСтройМаш-Финансы"',
                'description' => 'Финансово-экономический блок',
                'address' => 'г. Ростов-на-Дону, ул. Строительная, д. 1, корп. 3',
                'phone' => '+7 (863) 123-45-70',
                'email' => 'finance@donstroymash.ru',
                'parent_index' => 0,
            ],
            [
                'name' => 'ООО "ДонСтройМаш-Логистика-Автопарк"',
                'description' => 'Автопарк и грузоперевозки',
                'address' => 'г. Ростов-на-Дону, ул. Транспортная, д. 20А',
                'phone' => '+7 (863) 123-45-71',
                'email' => 'avtopark@donstroymash.ru',
                'parent_index' => 47,
            ],
            [
                'name' => 'ООО "ДонСтройМаш-Кадры-Обучение"',
                'description' => 'Центр обучения и развития',
                'address' => 'г. Ростов-на-Дону, ул. Строительная, д. 1, корп. 2А',
                'phone' => '+7 (863) 123-45-72',
                'email' => 'training@donstroymash.ru',
                'parent_index' => 48,
            ],
            [
                'name' => 'ООО "ДонСтройМаш-Финансы-Бухгалтерия"',
                'description' => 'Бухгалтерская служба',
                'address' => 'г. Ростов-на-Дону, ул. Строительная, д. 1, корп. 3, этаж 2',
                'phone' => '+7 (863) 123-45-73',
                'email' => 'buh@donstroymash.ru',
                'parent_index' => 49,
            ],
            [
                'name' => 'ООО "СтройМатериалы-Опт-Федеральный"',
                'description' => 'Федеральные оптовые поставки',
                'address' => 'г. Ростов-на-Дону, ул. Федеральная, д. 15',
                'phone' => '+7 (863) 456-78-96',
                'email' => 'federal@stroymaterialy.ru',
                'parent_index' => 10,
            ],
            [
                'name' => 'ООО "МашСтрой-Запчасти-Цех2"',
                'description' => 'Цех производства запчастей №2',
                'address' => 'г. Ростов-на-Дону, промзона Западная, д. 11',
                'phone' => '+7 (863) 345-67-97',
                'email' => 'ceh2@mashstroy.ru',
                'parent_index' => 9,
            ],
            [
                'name' => 'ООО "СтройПроект-Конструкции-КМ"',
                'description' => 'Проектирование металлических конструкций',
                'address' => 'г. Ростов-на-Дону, ул. Металлистов, д. 7',
                'phone' => '+7 (863) 567-89-09',
                'email' => 'km@stroyproekt.ru',
                'parent_index' => 13,
            ],
            [
                'name' => 'ООО "СтройПроект-Конструкции-КЖ"',
                'description' => 'Проектирование железобетонных конструкций',
                'address' => 'г. Ростов-на-Дону, ул. Бетонная, д. 14',
                'phone' => '+7 (863) 567-89-10',
                'email' => 'kzh@stroyproekt.ru',
                'parent_index' => 13,
            ],
            [
                'name' => 'ООО "ДонСтройМаш-Логистика-Снабжение"',
                'description' => 'Служба снабжения и закупок',
                'address' => 'г. Ростов-на-Дону, ул. Транспортная, д. 20Б',
                'phone' => '+7 (863) 123-45-74',
                'email' => 'snab@donstroymash.ru',
                'parent_index' => 47,
            ],
            [
                'name' => 'ООО "СтройКомплекс-Склад-Юг"',
                'description' => 'Южный складской комплекс',
                'address' => 'г. Ростов-на-Дону, промзона Южная, д. 2',
                'phone' => '+7 (863) 234-56-84',
                'email' => 'sklad-south@stroykomplex.ru',
                'parent_index' => 7,
            ],
            [
                'name' => 'ООО "МашСтрой-Сервис-Волгоград"',
                'description' => 'Волгоградский сервисный центр',
                'address' => 'г. Волгоград, пр. Ленина, д. 88',
                'phone' => '+7 (8442) 33-44-55',
                'email' => 'service-vlg@mashstroy.ru',
                'parent_index' => 8,
            ],
            [
                'name' => 'ООО "СтройКомплекс-Юг-Таганрог-Участок-Объект1-Этап1-СекцияБ"',
                'description' => 'Секция Б этапа 1 ЖК Северный (вложенность 7)',
                'address' => 'г. Таганрог, ул. Лизы Чайкиной, д. 5, корп. 1, секция Б',
                'phone' => '+7 (8634) 12-34-61',
                'email' => 'sekciya-b@stroykomplex-taganrog.ru',
                'parent_index' => 44,
            ],
            // ——— Новые родительские ветки с вложенностью ———
            [
                'name' => 'ООО "ДонСтройМаш-IT"',
                'description' => 'IT-подразделение холдинга',
                'address' => 'г. Ростов-на-Дону, ул. Строительная, д. 1, корп. 4',
                'phone' => '+7 (863) 123-45-75',
                'email' => 'it@donstroymash.ru',
                'parent_index' => null,
            ],
            [
                'name' => 'ООО "ДонСтройМаш-Недвижимость"',
                'description' => 'Управление недвижимостью и активами',
                'address' => 'г. Ростов-на-Дону, ул. Строительная, д. 1, корп. 5',
                'phone' => '+7 (863) 123-45-76',
                'email' => 'estate@donstroymash.ru',
                'parent_index' => null,
            ],
            [
                'name' => 'ООО "СтройКомплекс-Восток"',
                'description' => 'Восточный филиал СтройКомплекса',
                'address' => 'г. Ростов-на-Дону, ул. Восточная, д. 30',
                'phone' => '+7 (863) 234-56-88',
                'email' => 'vostok@stroykomplex.ru',
                'parent_index' => 1,
            ],
            [
                'name' => 'ООО "МашСтрой-Лизинг"',
                'description' => 'Лизинг строительной техники',
                'address' => 'г. Ростов-на-Дону, ул. Промышленная, д. 25А',
                'phone' => '+7 (863) 345-68-00',
                'email' => 'leasing@mashstroy.ru',
                'parent_index' => 2,
            ],
            [
                'name' => 'ООО "ДонСтройМаш-IT-Ростов"',
                'description' => 'Ростовский IT-офис',
                'address' => 'г. Ростов-на-Дону, ул. Пушкинская, д. 150',
                'phone' => '+7 (863) 123-45-77',
                'email' => 'it-rnd@donstroymash.ru',
                'parent_index' => 60,
            ],
            [
                'name' => 'ООО "ДонСтройМаш-IT-Краснодар"',
                'description' => 'Краснодарский IT-офис',
                'address' => 'г. Краснодар, ул. Красная, д. 130',
                'phone' => '+7 (861) 234-56-80',
                'email' => 'it-krd@donstroymash.ru',
                'parent_index' => 60,
            ],
            [
                'name' => 'ООО "ДонСтройМаш-IT-Ростов-Разработка"',
                'description' => 'Отдел разработки ПО',
                'address' => 'г. Ростов-на-Дону, ул. Пушкинская, д. 150, этаж 2',
                'phone' => '+7 (863) 123-45-78',
                'email' => 'dev@donstroymash.ru',
                'parent_index' => 64,
            ],
            [
                'name' => 'ООО "ДонСтройМаш-IT-Ростов-Инфраструктура"',
                'description' => 'Отдел IT-инфраструктуры',
                'address' => 'г. Ростов-на-Дону, ул. Пушкинская, д. 150, этаж 1',
                'phone' => '+7 (863) 123-45-79',
                'email' => 'infra@donstroymash.ru',
                'parent_index' => 64,
            ],
            [
                'name' => 'ООО "ДонСтройМаш-IT-Разработка-Проект ERP"',
                'description' => 'Проект внедрения ERP',
                'address' => 'г. Ростов-на-Дону, ул. Пушкинская, д. 150, оф. 201',
                'phone' => '+7 (863) 123-45-80',
                'email' => 'erp@donstroymash.ru',
                'parent_index' => 66,
            ],
            [
                'name' => 'ООО "ДонСтройМаш-IT-Разработка-Проект CRM"',
                'description' => 'Проект внедрения CRM',
                'address' => 'г. Ростов-на-Дону, ул. Пушкинская, д. 150, оф. 202',
                'phone' => '+7 (863) 123-45-81',
                'email' => 'crm@donstroymash.ru',
                'parent_index' => 66,
            ],
            [
                'name' => 'ООО "ДонСтройМаш-IT-Проект ERP-Модуль Документооборот"',
                'description' => 'Модуль электронного документооборота',
                'address' => 'г. Ростов-на-Дону, ул. Пушкинская, д. 150, оф. 201А',
                'phone' => '+7 (863) 123-45-82',
                'email' => 'edo@donstroymash.ru',
                'parent_index' => 68,
            ],
            [
                'name' => 'ООО "ДонСтройМаш-Недвижимость-Управление активами"',
                'description' => 'Управление недвижимыми активами',
                'address' => 'г. Ростов-на-Дону, ул. Б. Садовая, д. 150',
                'phone' => '+7 (863) 123-45-83',
                'email' => 'assets@donstroymash.ru',
                'parent_index' => 61,
            ],
            [
                'name' => 'ООО "ДонСтройМаш-Недвижимость-Аренда"',
                'description' => 'Служба аренды помещений',
                'address' => 'г. Ростов-на-Дону, ул. Б. Садовая, д. 151',
                'phone' => '+7 (863) 123-45-84',
                'email' => 'rent@donstroymash.ru',
                'parent_index' => 61,
            ],
            [
                'name' => 'ООО "Недвижимость-Управление-Жилой фонд"',
                'description' => 'Управление жилым фондом',
                'address' => 'г. Ростов-на-Дону, ул. Красноармейская, д. 70',
                'phone' => '+7 (863) 123-45-85',
                'email' => 'housing@donstroymash.ru',
                'parent_index' => 71,
            ],
            [
                'name' => 'ООО "Недвижимость-Жилой фонд-ЖК Западный"',
                'description' => 'Жилой комплекс Западный',
                'address' => 'г. Ростов-на-Дону, ул. Малиновского, д. 100',
                'phone' => '+7 (863) 123-45-86',
                'email' => 'jk-zapad@donstroymash.ru',
                'parent_index' => 73,
            ],
            [
                'name' => 'ООО "Недвижимость-ЖК Западный-Корпус 1"',
                'description' => 'Корпус 1 ЖК Западный',
                'address' => 'г. Ростов-на-Дону, ул. Малиновского, д. 100, корп. 1',
                'phone' => '+7 (863) 123-45-87',
                'email' => 'jk-zapad-k1@donstroymash.ru',
                'parent_index' => 74,
            ],
            [
                'name' => 'ООО "Недвижимость-ЖК Западный-Корпус 2"',
                'description' => 'Корпус 2 ЖК Западный',
                'address' => 'г. Ростов-на-Дону, ул. Малиновского, д. 100, корп. 2',
                'phone' => '+7 (863) 123-45-88',
                'email' => 'jk-zapad-k2@donstroymash.ru',
                'parent_index' => 74,
            ],
            [
                'name' => 'ООО "СтройКомплекс-Восток-Волгодонск"',
                'description' => 'Представительство в Волгодонске',
                'address' => 'г. Волгодонск, ул. Морская, д. 25',
                'phone' => '+7 (8639) 22-33-44',
                'email' => 'volgodonsk@stroykomplex.ru',
                'parent_index' => 62,
            ],
            [
                'name' => 'ООО "СтройКомплекс-Восток-Новочеркасск"',
                'description' => 'Представительство в Новочеркасске',
                'address' => 'г. Новочеркасск, пр. Платовский, д. 80',
                'phone' => '+7 (8635) 24-35-46',
                'email' => 'novocherkassk@stroykomplex.ru',
                'parent_index' => 62,
            ],
            [
                'name' => 'ООО "Восток-Волгодонск-Склад"',
                'description' => 'Складской комплекс в Волгодонске',
                'address' => 'г. Волгодонск, промзона Северная, д. 5',
                'phone' => '+7 (8639) 22-33-45',
                'email' => 'sklad-vgd@stroykomplex.ru',
                'parent_index' => 77,
            ],
            [
                'name' => 'ООО "Восток-Волгодонск-Склад-Зона А"',
                'description' => 'Складская зона А в Волгодонске',
                'address' => 'г. Волгодонск, промзона Северная, д. 5А',
                'phone' => '+7 (8639) 22-33-46',
                'email' => 'zona-a-vgd@stroykomplex.ru',
                'parent_index' => 79,
            ],
            [
                'name' => 'ООО "Восток-Волгодонск-Склад-Зона А-Сектор 1"',
                'description' => 'Сектор 1 зоны А Волгодонск',
                'address' => 'г. Волгодонск, промзона Северная, д. 5А-1',
                'phone' => '+7 (8639) 22-33-47',
                'email' => 'sector1-vgd@stroykomplex.ru',
                'parent_index' => 80,
            ],
            [
                'name' => 'ООО "МашСтрой-Лизинг-Юг"',
                'description' => 'Южное региональное отделение лизинга',
                'address' => 'г. Ростов-на-Дону, ул. Портовая, д. 50',
                'phone' => '+7 (863) 345-68-01',
                'email' => 'leasing-yug@mashstroy.ru',
                'parent_index' => 63,
            ],
            [
                'name' => 'ООО "МашСтрой-Лизинг-Юг-Ростов"',
                'description' => 'Ростовский офис лизинга',
                'address' => 'г. Ростов-на-Дону, ул. Портовая, д. 50А',
                'phone' => '+7 (863) 345-68-02',
                'email' => 'leasing-rnd@mashstroy.ru',
                'parent_index' => 82,
            ],
            [
                'name' => 'ООО "Лизинг-Ростов-Отдел продаж"',
                'description' => 'Отдел продаж лизинга',
                'address' => 'г. Ростов-на-Дону, ул. Портовая, д. 50А, этаж 1',
                'phone' => '+7 (863) 345-68-03',
                'email' => 'leasing-sales@mashstroy.ru',
                'parent_index' => 83,
            ],
            [
                'name' => 'ООО "Лизинг-Ростов-Отдел договоров"',
                'description' => 'Отдел договоров лизинга',
                'address' => 'г. Ростов-на-Дону, ул. Портовая, д. 50А, этаж 2',
                'phone' => '+7 (863) 345-68-04',
                'email' => 'leasing-contracts@mashstroy.ru',
                'parent_index' => 83,
            ],
        ];

        $organizations = [];

        foreach ($organizationsData as $index => $orgData) {
            $parentIndex = $orgData['parent_index'];
            unset($orgData['parent_index']);

            $organization = new Organization();
            $organization->setName($orgData['name']);
            $organization->setDescription($orgData['description']);
            $organization->setAddress($orgData['address']);
            $organization->setPhone($orgData['phone']);
            $organization->setEmail($orgData['email']);

            if (null !== $parentIndex && isset($organizations[$parentIndex])) {
                $organization->setParent($organizations[$parentIndex]);
            }

            $manager->persist($organization);
            $organizations[$index] = $organization;

            $this->addReference('organization_' . ($index + 1), $organization);
        }

        $manager->flush();
    }
}
